### ISSUE TITLE
Create folder structure in Google Project Drive

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#1]
### Overview
The Org needs to have a folder structure for  the guides inside of the Organizations Google Drive: Hack for LA Guides, so that we do not loose access to the files.

### Action Items
- [x] Create new folders that mimic the folder structure from the current shortcut folder
- [x] Write guidance for the CoP leads that tells them to give permission level contributor to their members when they add them to the Organizations Google Drive: Hack for LA Guides
- [x] Give access to the Organizations Google Drive: Hack for LA Guides to all Community of Practice Leads (Manager) and the guidance.  
- [ ] Message on slack about it.

### Resources/Instructions

- [Current location of shortcuts to be made into folders](https://drive.google.com/drive/folders/1buzmMJ5gCMvm3mpmdqDWryI6IBA8foKA?usp=sharing)
- [Organizations Google Drive: Hack for LA Guides](https://drive.google.com/drive/folders/1LAE_-KUd72u7vTBOTwU1Rz83rTCbeWB_?usp=sharing)
- [Adding Members to Organization's Google Drive [DRAFT]](https://docs.google.com/document/d/1qMfBWrtwzhzknydWHbqrGwkfbRkNhoCUHWjgjWaePe0/edit?usp=drive_web&ouid=113215052388734356505)
- [CoP Leads Roster Sheet](https://docs.google.com/spreadsheets/d/1aAvig46CQirT5kWxcf4MdeNMcE63QtuOSvbnNzejS_8/edit?usp=sharing)

**Comment by gautham-l** [comment]
@ExperimentsInHonesty How about I download all the folder structures, templates and upload them to Organizations Google Drive: Hack for LA Guides? Later I can add collaborators to each folder and assign the respective members as owners to documents.

**Comment by ExperimentsInHonesty** [comment]
@gautham-l lets do a tiny test with one folder structure and see what happens to the edit history and ownership.  But please do that on a shared drive that you create, so that it doesn't affect our Organizations Google Drive: Hack for LA Guide folder.

**Comment by gautham-l** [comment]
[Link](https://docs.google.com/document/d/1qMfBWrtwzhzknydWHbqrGwkfbRkNhoCUHWjgjWaePe0/edit?usp=drive_web&ouid=113215052388734356505) to guidance for the CoP leads. ETA of completion will be the end of this week.

**Comment by gautham-l** [comment]
> @gautham-l lets do a tiny test with one folder structure and see what happens to the edit history and ownership. But please do that on a shared drive that you create, so that it doesn't affect our Organizations Google Drive: Hack for LA Guide folder.

Able to copy collaborators however, not able to copy version histroy.

**Comment by ExperimentsInHonesty** [comment]
One other reason that we might not use the download and reupload version, is that we potentially loose the original urls of the files and those urls are linked in the projects, Issues, Projectboard cards and WIKI

**Comment by gautham-l** [comment]
1. Completed [Adding Members to Organization's Google Drive [DRAFT]](https://docs.google.com/document/d/1qMfBWrtwzhzknydWHbqrGwkfbRkNhoCUHWjgjWaePe0/edit#).
2. Need to get a list of CoP leads from @ExperimentsInHonesty.

**Comment by ExperimentsInHonesty** [comment]
https://www.hackforla.org/communities-of-practice

https://github.com/hackforla/communities-of-practice
UI/UX 
Ryan Curtis
Felicia Swafford
Kevin Wang
Tan Zhou

Product Management (Olivia and Ebele)
Ops (bonnie@hackforla.org)
Marketing (Bonnie and Mike Chiuasno)
Data Science Ryan Swan and Sophia Alice
Revenue (Chelsey Beck and Bonnie and Melissa Mae Cruz)
Engineering (Grew Pawin and Qiqi Zheng)

**Comment by ExperimentsInHonesty** [comment]
Olivia has setup the template for making an issue on the Shared Drive migration, please add the instructions to that document
https://github.com/hackforla/product-management/issues/268

**Comment by gautham-l** [comment]
Content Manager access is given 13 CoP Leads (Parent and sub folders of all teams) using email addresses from CoP [roster sheet](https://docs.google.com/spreadsheets/d/1aAvig46CQirT5kWxcf4MdeNMcE63QtuOSvbnNzejS_8/edit?usp=sharing).

**Comment by ExperimentsInHonesty** [comment]
We are closing this issue because it has been replaced by  #7
