### ISSUE TITLE
Onboarding: Prakhar Singh

### ISSUE THREAD

**Issue by designer2209** [hackforla/guides#100]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [x] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [ ] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather presentation - Prakhar](https://docs.google.com/document/d/11-DsvNj36EXL8pZSrTCwDI_KsM9qtGA3GbOGQ9HT0pI/edit?usp=sharing)
- Guide you are working on
   - Name of guide: Guide: How to Present Your Work (UX Research)
   - URL of guide Issue: https://github.com/hackforla/UI-UX/issues/24

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by designer2209** [comment]
Progress: Selected a Guide to work on [How to Present Your Work (UX Research)](https://github.com/hackforla/UI-UX/issues/24), Reached Slide 12 of GP: How to Gather Examples and Interview Teams (CoP presentation).

Blockers: Stuck on slide 12 right now so trying to understand the process as I go through the PPT.

Availability: I should have about 6 hours, more if I don't get too much workload.

ETA: Apologies but I can't say for sure, I just took on the issue so I need to go through the documentation of the issue itself and the "How to gather example" ppt.

Pictures (if necessary): Currently there aren't any to share right now.

**Comment by SheIsBukki** [comment]
@designer2209 Thanks for your update, you can reach out if you are still stuck. I've also checked your observations, and we will review and try to resolve them at the next meeting. Your ETA doesn't have to be a specific time, not knowing when is also a good ETA 😊

**Comment by ExperimentsInHonesty** [comment]
Resolved comments today.    Also added several new slides to the Slack method 4.  @designer2209 will add some more slides with instructions after [slide 22](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g123155bdeed_1_28) in order to make it clear to new people how to find the items once they viewed the specific comment in the slack.

**Comment by designer2209** [comment]
Added [Slide 23](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10c22cb8a35_0_99) and [Slide 24](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g12315607cfb_2_1). Slide 23 has a video embedded into it and you can find that video in my drive [Hack4LA Guides-Gather Example Method 4.mp4](https://drive.google.com/file/d/1VRsQAMz9WY9uaJwGwJAMCj7_GmFQFcnX/view?usp=sharing). Take a look at the slides and if there are any other changes to be made please do let me know.

**Comment by designer2209** [comment]
Progress: Currently working on the Guide: How to Present Your Work (UX Research), to be specific I am going through 311 Data's slack channel and gathering examples. I've added some info in the [comments](https://github.com/hackforla/UI-UX/issues/24#issuecomment-1087968196) section of the Guide itself.

Blockers: No blockers as of now.

Availability: I have a couple of interviews and 2 side projects this week so I don't know how often I'll be available, but I will try to be put in as much time as I can.

ETA: I think I might be able to go through 311 Data's slack channel within a two to three days.

Pictures (if necessary):
![image](https://user-images.githubusercontent.com/83784264/161625534-f2525a4b-a714-45c1-934a-a24d37f5db0d.png)

**Comment by designer2209** [comment]
- Updated the video in [Slide 23](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10c22cb8a35_0_99) and uploaded the video in [HackforLA's Google drive](https://drive.google.com/file/d/1_-XfN0kLsZg7PYiha4w0hNtTfOQgOVk8/view?usp=sharing).

- Progress: Still working on the Guide: How to Present Your Work (UX Research), I've gone through the slack channels of
  100 Automations
  311 Data
  Access the Data
  BallotNav

  Civic Tech Index
  Civic Tech Jobs

- Blockers: No blockers as of now.

- Availability: I have to work on a Design assignment as a part of the hiring process, once I am done with that I'll start working on gathering examples from the remaining projects' slack channels.

- ETA: I honestly have no idea

**Comment by designer2209** [comment]
Progress: Gone through the [GP: How to Gather Examples and Interview Teams (CoP presentation)](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfa2faf6700_0_3) completely and added a few more points in the [GT: Notes on Gather presentation - Prakhar](https://docs.google.com/document/d/11-DsvNj36EXL8pZSrTCwDI_KsM9qtGA3GbOGQ9HT0pI/edit) document. I'll be going through the PPT again and think of ways to simplify the content so that new members can follow it without any difficulty and also continue with example gathering for the issue [Guide: How to Present Your Work (UX Research) #24](https://github.com/hackforla/UI-UX/issues/24).

Blockers: No Blockers.

Availability: I have about 6-10 this week for the issues.

ETA: I've gone through half of the list of "Projects to be checked" till now so I think another 2 weeks at least.

Pictures (if necessary): No pictures this time.

**Comment by designer2209** [comment]
Update the word document [GT: Notes on Gather presentation - Prakhar](https://docs.google.com/document/d/11-DsvNj36EXL8pZSrTCwDI_KsM9qtGA3GbOGQ9HT0pI/edit) with the following:

[Slide 7](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g117fac9d1a0_0_50): Added the remaining CoPs in the list, only the ones that had “Templated and Guides” board link on the [Community of Practice Guide Project Boards](https://github.com/hackforla/guides/wiki/Community-of-Practice-Guide-Project-Boards) on GitHub.

[Slide 16](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g11b172cbaeb_1_0): Added a new screenshot for “Finding Examples: Method 1 Exercise”, the text in the slide says “Let’s try Method 2 together!” Should I remove that? Because that slide is a continuation of[ Slide 15](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_124).

[Slide 18](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g11b172cbaeb_1_13): Made slight adjustments to the content on the slide.

[Slide 19:](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10f03f8e69a_3_1) Added a screenshot for an example where we did find some results by looking at the issue tab.

[Slide 42:](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g11b17a47af5_0_3) Added this slide and the screenshot mentioned in the table above for Slide 41.

Flowchart for [Slide 33](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g106b19fa3e4_0_87) remains, I'll be doing that over this weekend.

**Comment by ExperimentsInHonesty** [comment]
We covered all the comments above.  Prakar will make additional changes.

**Comment by designer2209** [comment]
- Replaced the screenshot of the filter bar on [Slide 18](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g11b172cbaeb_1_13) with a longer one and with a keyword ("presentation") typed into it for better understanding.

- Added new screenshots on [Slide 19](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10f03f8e69a_3_1), they need to be reviewed.

- Replaced the old screenshot of "Sub Issue" with an updated one on [Slide 43](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g121e6985d41_1_15)

**Comment by ExperimentsInHonesty** [comment]
Looked at slides above

- Slide 19 still needs new screenshots.  Note on the slide.
> fix the screenshots - size of the items inside the screen need to be the same and the comments need to be the same color.
> 
> bottom left results should be similar to bottom right, but with details about what you found.

- Talked about flowchart. 
> Let's make this in figjam in the team file area: [https://www.figma.com/files/team/1021794324698928161/Guides](https://www.google.com/url?q=https://www.figma.com/files/team/1021794324698928161/Guides&sa=D&source=editors&ust=1650298166061078&usg=AOvVaw0Vaj-tmcdFqWjxG84O9A4C) using the template for flowchart.

**Comment by designer2209** [comment]
- Made the changes in the [Figjam file](https://www.figma.com/file/iTlg02Ux1OvkiYvoC7aXp8/How-to-Gather-Examples-Flowchart?node-id=0%3A1) mentioned during the meeting.

- Will work on the screenshots tomorrow.

**Comment by SheIsBukki** [comment]
> * Made the changes in the [Figjam file](https://www.figma.com/file/iTlg02Ux1OvkiYvoC7aXp8/How-to-Gather-Examples-Flowchart?node-id=0%3A1) mentioned during the meeting.
> * Will work on the screenshots tomorrow. 


@designer2209 How's it going with the screenshots?

**Comment by designer2209** [comment]
I have yet to take the screenshots, I have some job interview related work which usually doesn't take long but I haven't been feeling well so it might take longer than expected, but I will do it before Monday's meeting.

**Comment by designer2209** [comment]
- Update: 
- I've added 3 screenshots (Upper left, Lower left and Upper right) I am unsure whether they are accurate representation of the "Method" mentioned in the slide so I might need a feedback during Monday's meeting.

- I've uploaded a screenshot of the flowchart as well but due to the amount of content in the chart I think it's not properly visible so I am thinking of making a flowchart using Google Slide's in-built shapes.

**Comment by SheIsBukki** [comment]
@designer2209 Thanks for the update, Bonnie will review the screenshots at the next meeting.

**Comment by ExperimentsInHonesty** [comment]
Prakar  will change the shape of the diamonds to parallelogram on [slide 38](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g124ce1f2c2b_1_31)

**Comment by designer2209** [comment]
Couldn't find the link to [PeopleDepot's](https://github.com/hackforla/peopledepot) slack channel in HackforLA's [projects list](https://www.hackforla.org/projects/)

**Comment by designer2209** [comment]
- Progress: Finished going through the Slack channels of every project from the list. Went through the Wiki's of 100 Automation and 311 Data.

- Blockers: No Blockers. But I wanted to know about 311 Data project and where could I find some information about how the project was done, the data mining and visual presentation of the data onto the map.

- Availability: I should have about 6-8 hours.

**Comment by designer2209** [comment]
Personal Query - What exactly is the "Code for...." orgs
- [list of all orgs that need to be in the index](https://docs.google.com/document/d/1ouaGcDHUbF28El4SqOBTlUu5RmBfmRI5QDfU1TVXXjo/edit)

**Comment by SheIsBukki** [comment]
@designer2209 Thanks for sharing updates consistently 😀

**Comment by designer2209** [comment]
Progress: I've finished looking for examples in the wikis of all the projects, will be moving onto the next steps (looking at the Project Board Card Links and then connecting with the design managers of each project on slack).

Blockers: No Blockers. But I wanted to know about 311 Data project and where could I find some information about how the project was done, the data mining and visual presentation of the data onto the map and also a bit of information about the Internship project, how it is supposed to work, how any work the interns do for Hack4LA would be considered legitimate enough for them to have better job prospects in the future etc.

Availability: I should have about 6 hours this week.

**Comment by ExperimentsInHonesty** [comment]
311 Tech: React, Redux, Material-UI, Mapbox, AWS, FastAPI, Redis, PostgreSQL, Prefect, Docker

**Comment by designer2209** [comment]
Started gathering examples from the Issues Tab of the projects.

Need access to some files to review them, I have mentioned them in my [comment](https://github.com/hackforla/UI-UX/issues/24#issuecomment-1147220279) on the guide issue.

I might have about 4-6 hours this week as I now have a job (yay).

**Comment by designer2209** [comment]
Finished gathering examples from the Issues Tab of the projects and will be moving on to the "Project Board Card Links", throughout the next week (hopefully will be done before next Friday).

Need access to some files to review them, I have mentioned them in my [comment](https://github.com/hackforla/UI-UX/issues/24#issuecomment-1155462835) on the guide issue.

**Comment by ExperimentsInHonesty** [comment]
I gave access to all the assets and found some additional links for @designer2209

**Comment by designer2209** [comment]
Added a note in the [GT: Notes on Gather presentation - Prakhar](https://docs.google.com/document/d/11-DsvNj36EXL8pZSrTCwDI_KsM9qtGA3GbOGQ9HT0pI/edit?usp=sharing) regarding confusion I had on [Method 3](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_168)

**Comment by designer2209** [comment]
- Progress: Currently I am gathering examples from the Project Board card links and will be updating my guide issue accordingly.

- Blockers: No blockers as of yet.

- Availability: This week I have about 4-5 hours

- ETA: Not sure, the project board card link shouldn't take too long, hopefully it'll be done before Monday.

**Comment by designer2209** [comment]
Progress: I haven't gone through all the project board card links yet, the ones after Green Earth Oasis are remaining.

Blockers: No blockers as of yet.

Availability: The coming week I have about 4 hours

ETA: By Tuesday (2nd August)

**Comment by designer2209** [comment]
Started connecting with other teams on Slack, will keep a log of all the conversations that takes place in the slack channel in this [comment](https://github.com/hackforla/UI-UX/issues/24#issuecomment-1201304638)

**Comment by designer2209** [comment]
Progress: I have been able to connect with members of 100 Automations, 311 Data, Access the Data, BallotNav, Civic Opportunity, Civic Tech (Index, Jobs), Design System, Engage and Expunge Assist regarding what their Lead UX Researchers or Project Managers are using as a template or a guideline to present their UX research work. The updated communication summary is linked onto this [comment](https://github.com/hackforla/UI-UX/issues/24#issuecomment-1201304638).

Blockers: Haven't had a response from Civic Opportunity, and apart from the projects that I reached out to recently only BallotNav had some sort of template to share which is present in my guide issue as well.

[BallotNav Communications Guide for Document Creation INTERNAL to present their UX Research work](https://docs.google.com/presentation/d/1240MJDl2PA6NcchLwVdGvweI-dC_E4u4-V8jmHNz_LI/edit#slide=id.g8078b36bb8_0_35)

Availability: This week I am available for 6 hours

ETA: Not sure, the time difference slows down the communication aspect and I have some personal work to deal with so I am less online than usual.

**Comment by designer2209** [comment]
I've rephrased my messages on Slack that I've sent to the Lead UX researchers or PMs of the respective projects. Hopefully I was able to do it right this time, I have updated them in the [comment](https://github.com/hackforla/UI-UX/issues/24#issuecomment-1201304638) of my guide issues as well.

**Comment by designer2209** [comment]
Hi @edwardsarah, apologies for the late response and at this point of time I am unfortunately unable to commit any time to the Guides Teams as of now so you could go ahead offboard me.

Again, apologies for any inconveniences. 😓

**Comment by edwardsarah** [comment]
Ok, I will close this issue then. Thank you for all of the work you've done!
