### ISSUE TITLE
Outstanding items for the Gather Examples presentation

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#105]
### Overview
We need to make a list of final items for the gather examples presentation so that we can finish it off

### Action Items
- [ ]  Identify which slides still have notes on them
   - [ ] Fix formatting issues
      - [x] Titles all at the same height
      - [x] All screenshots have drop shadows
      - [ ] Type in consistent color and sizing
   - [x] [Table of Contents](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gf36302a57a_0_277)
      - [x] relink all the slides (after all slides are complete)
   - [x] Add a [Glossary Slide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10c22cb8a35_0_0)
   - [x] [What is a Guide?](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g12535235506_2_6)
      - [x] Add more examples
   - [x] [Finding Examples: Method 5: Resource Provided](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g11f232f4864_1_2)
      - [x] Add benefit info (if we decide we want it)
   - [x] [How to Connect with Other Teams](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_64)
      - [x] We need to find an example where the issue has not been updated in a while and see how we would recommend adding a note to it, and following up with slacking them, etc.
      - [x] Replace text with sample image of message text
   - [x] [How to Move the conversation forward](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g12535235506_2_27)
      - [x] find Research plan guide
      - [x] Add link to fake notes, telling people to look at 
         - [x] TDM calc wiki, research page
         - [x] Hack for LA website wiki, research
- [x] Add authors to the [last slide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g13af5136844_0_0)
  - [x] Add last names to all contributors
  - [x] Add links to linkedin profiles for every contributor
- [x] Monitor these slack thread to determine if it still shows up in another week, and how long can we retain all its messages?  Editing [slide with Slack warning](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10c22cb8a35_0_88) with updated Guidance.  Second slack link has two versions, see if that makes a difference
  - [ ] [Slack Thread 1](https://hackforla.slack.com/archives/C01H0HUDMCK/p1648743050350109)
  - [ ] [Slack thread 2.a](https://hackforla.slack.com/archives/C018S5TCQE7/p1647384705876399?thread_ts=1647257120.783349&cid=C018S5TCQE7) 
  - [ ] [Slack thread 2.b](https://hackforla.slack.com/archives/C018S5TCQE7/p1647257120783349)
  - [ ] See screenshots below for whole message thread
- [ ] Address notes
- [x] Add content to slide 36 - Method 4 / Using slack to find resources
- [x] Add content to slide 26 - Method 2 / Finding issues on the issue tab
- [x] Slide(s) How to annotate findings for Method 1, 3, 5. Update 4

### Resources/Instructions
[GP: How to Gather Examples and Interview Teams (CoP presentation)](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.gfcb8642ab3_2_37)

<details>
<summary>Screenshots of slack thread for checking dates 1</summary>

![image](https://user-images.githubusercontent.com/37763229/167169514-18b4ea93-0b16-44aa-ad8c-1b057aec606e.png)
![image](https://user-images.githubusercontent.com/37763229/163831418-6d439dc4-50e9-46cb-b4dd-175cfb88c2af.png)
![image](https://user-images.githubusercontent.com/37763229/167164586-b3bb7589-5e34-46bc-989c-558ca77608df.png)
</details>

<details>
<summary>Screenshots of slack thread for checking dates 2</summary>

![image](https://user-images.githubusercontent.com/37763229/167174599-fcda6d2a-9abe-418a-a958-6225f1d9e775.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
We are not going to address this now, but it's a legitimate potential outreach avenue, that we should keep looking as we evolve to see if there is a way to address this that is productive
![image](https://user-images.githubusercontent.com/37763229/166717074-8cc37de8-b11c-4f6a-b228-ea82aa2c3b9a.png)

**Comment by edwardsarah** [comment]
Remaining edits needed for the presentation to go over on Monday (8/1):
- Slide 26 needs an explanation of why we look at issues to find examples/info for a guide
- Slide 36 needs an explanation of what we use the slack for / why we look at it to find examples
- Need to add a slide (or multiple slides) on how to properly document examples when you find them using Method 1, 3, 4, and 5
- Slack information needs to be updated with how links to threads can be preserved past the slack message limit. Ideally this is taken on by someone who knows the right way to do this
- Last slide needs full list of authors, with last names, and linkedin profiles linked

When everything else is resolved:
- Fix the table of contents and make sure it leads to the right place within the slides
- Fix any weird formatting issues (ex. make sure all text is the right color and size, there is uniformity in when grey or orange boxes are used, titles are at the right height, etc.)

**Comment by edwardsarah** [comment]
Breakdown of Slides 
**1-11:** What is a guide **[12 Slides]**
**12-20:** Picking a Guide & Setup (assigning yourself & adding projects) **[9 Slides]**
**22:** Where to Find Examples 
**23-26:** Searching Project Wikis **[4 Slides]**
**27-31:** Issues Tab **[5 Slides]**
**32-37:** Project Board Cards **[6 Slides]**
**38-50:** Slack **[13 Slides]**
_(38-44)_ Searching Slack Threads **[7 Slides]**
_(45-48)_ Searching Slack Files **[4 Slides]**
_(49 & 50)_ Annotating Findings **[2 Slides]**
**51 & 52:** Resources Provided **[2 Slides]**
**53:** Section Wrap Up
**54 & 55:** Connect w/ Other Teams Section Heading
**56-61:** How to Connect w/ Other Teams **[6 Slides]**
**62-69:** How to Move the Conversation Forward **[8 Slides]**
**70-78:** How to Organize a Special Issue **[9 Slides]**
**79 & 80:** How to Interview Practitioners
**81:** Section Wrap Up
**82 & 83:** Check w/ Org Representative
**84-89:** Wrap Up [6 Slides] 

Qs
- Do we expect to continue to have a project board section after Github transitions to the new project board system? It is useful for getting folks up to speed with how HfLA uses github but project board cards themselves will not be relevant.
- Should we try to consolidate the slack section? The slides are fast to move through but it seems like too much of the presentation to spend on using the method.
- Similarly, it feels like the section on moving the conversation forward could be cut down given how clear the flowchart is.

**Comment by SheIsBukki** [comment]
@ExperimentsInHonesty Sarah finished with the action items in this issue, please review.

**Comment by edwardsarah** [comment]
8/12 we discussed breaking the slides into smaller presentations that are easier to navigate and focus on specific issues (as opposed to one presentation that covers absolutely everything). With a mind to videos that are <5mins and cover one topic at a time, here's how I think we should split them up: 

1. **[4-20]:** What is a Guide & Picking your First guide
   a. Could also separate out Picking Your First Guide, and using this as a section to provide an overview on gathering examples + go over checking the resources provided
2. **[21-26]:** Gathering Examples pt.1: Wiki
3. **[27-31]:** Gathering Examples pt.2: Issues Tab
4. **[32-37]:** Gathering Examples pt.3: Project Board
5. **[38-50]:** Slack
6. **[56-60]:** How to Connect w/ Other Teams
7. **[61-67 + 77-78]:** Moving the Conversation Forward & How to Interview Practitioners
8. **[68-76 + 81]:** Making a Special Issue & Last Check w/ Org Rep

Alt Breakdown for Fewer but Longer Presentations:
1. **[4-20]:** What is a Guide & Picking Your First Guide _(17 Slides)_
2. **[22-37 + 51-52]:** Gathering Examples: Github [Wiki, Issues, Project Board, Resources Provided] _(18 Slides)_
3. **[38-50]:** Gathering Examples: Slack _(13 Slides)_ 
4. **56-67 + 77-78:** How to Connect w/ Other Teams, Moving the Conversation Forward, How to Interview Practitioners _(14 Slides)_
5. **[68-76 + 81]:** Making a Special Issue & Last Check w/ Org Rep _(10 Slides)_

**Comment by edwardsarah** [comment]
At the Monday meeting (8/15) Bukki and I split the gather examples presentation into smaller slide decks based on the second breakdown above. 
[What is a Guide & Picking Your First Guide](https://docs.google.com/presentation/d/1WvHkRja7McjraE-QIjMSPluEOwBbLhFletlCYnzGLb0/edit?usp=sharing)
[Gathering Examples: Github [Wiki, Issues, Project Board, Resources Provided]](https://docs.google.com/presentation/d/1XWY-OMiomzpKw_aCL1JkdgAhqpgGDZ2bu_XuReTO1zw/edit?usp=sharing)
[Gathering Examples: Slack](https://docs.google.com/presentation/d/1-Kg7yLRXsdGo4Ln8L-WiunOOO3Uc7TuXvH5afcp3AKQ/edit?usp=sharing)
[How to Connect w/ Other Teams, Moving the Conversation Forward, How to Interview Practitioners](https://docs.google.com/presentation/d/15WxdSc_YFVLdytCZ-SxZaWPt8y6-OQTxJb8dcppZHVE/edit?usp=sharing)
[Making a Special Issue & Last Check w/ Org Rep](https://docs.google.com/presentation/d/1egg1WUxIt9lz4mFXiR7OeKb6dTz-5HCxi5Ai8uEL4Ps/edit?usp=sharing)
