### ISSUE TITLE
Onboarding: Sarah Edwards

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#108]
### Prerequisite
- You have done the steps in this wiki page for onboarding new team members https://github.com/hackforla/guides/wiki/Joining-the-Team

### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [ ] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [ ] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [ ] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [ ] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- hackforla/product-management#88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather presentation - Sarah Edwards](https://docs.google.com/document/d/13h87nNLOOEwm9Gu6a5XO7p5I-UyBXBriw31BpxZr4IA/edit) 
- Guide you are working on
   - Create a Guide/Template: Presentation deck for your project
   - https://github.com/hackforla/knowledgebase-content/issues/24

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by edwardsarah** [comment]
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" 
I've done an initial pass through the wikis, issues, and project boards for almost all of the active projects. I've followed the presentation on gathering examples until about slide 32. I still need to go through the wikis, issues, and project boards for 100 Automations and the Hack for LA website. 
2. Blockers: "Difficulties or errors encountered." Some projects have presentations that I don't have access to. Will create an issue for that and link it here later. 
3. Availability: "How much time will you have this week to work on this issue?" at least 4hrs.
4. ETA: "When do you expect this issue to be completed?" Unclear. Not sure how much work will be required to find examples for the remaining projects. 
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
@ExperimentsInHonesty Sarah needs access to these https://github.com/hackforla/product-management/issues/183#issuecomment-1159922485

**Comment by edwardsarah** [comment]
Progress: Finished looking at the slack channels for all of the active projects except Brigade Organizer's Playbook. 
Blockers: Waiting on access to the Code for America slack to check the Brigade Organizer's Playbook channel, which could take a few hours. Haven't yet gotten access to files listed above, will reach out to the teams directly if not resolved this weekend.
Availability: This weekend, 1-2 hours. The upcoming week I will have at least 5 hours. 
ETA: Still unclear, I imagine talking to teams will take a few weeks to coordinate and complete.
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by edwardsarah** [comment]
Progress: Finished looking at project boars for Hack for LA's website and the internship project. This week i'm hoping to take a final look for any resources in wikis/issues/slack and start reaching out to teams. 
Blockers: Just the issue with file access. No new blockers.
Availability: 4+ hours between now and Friday
ETA: Still unclear.
Pictures (if necessary):

**Comment by edwardsarah** [comment]
Progress: Less than anticipated, started making a list of people on each team to contact. This weekend I will reach out to all teams that I don't yet have examples from to see if they have presentation decks they can share with me. 
Blockers: None
Availability: At least 3 hours on Sunday
ETA: Still unclear.
Pictures (if necessary):

**Comment by ExperimentsInHonesty** [comment]
Hi @edwardsarah it looks like the monday is a holiday (4th of july).  So our next team meeting is Friday the 8th. Looking forward to seeing you there.  I'll get you access to the files today, that you don't currently have.

**Comment by ExperimentsInHonesty** [comment]
looking forward to going over the comment in your [notes doc](https://docs.google.com/document/d/13h87nNLOOEwm9Gu6a5XO7p5I-UyBXBriw31BpxZr4IA/edit) with you. on 2022-07-08

**Comment by edwardsarah** [comment]
Progress: Started reaching out to teams I don't have examples from yet, including Access the Data and Civic Tech Jobs. I've been cross referencing PMs listed on the website with ones active on github/slack which has taken a bit of extra time. 
Blockers: Some teams aren't listed on the website (I think the Internship project, tables, and people depot) or don't have PMs listed (lucky parking sort of, food oasis)
Availability: A couple hours this weekend. Starting Wednesday I am on vacation until next Tuesday.
ETA: Still unclear.
Pictures (if necessary):

**Comment by edwardsarah** [comment]
Added slides to gather examples presentation on searching slack channel files. 
[beginning of new slides] (https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g13bdf6a6b5a_0_3)

**Comment by edwardsarah** [comment]
since we didn't get to discuss the slides I added at the meeting today (7-11-22), it would be helpful if the team could look over them and leave any comments about where the instructions might be unclear or unnecessarily detailed so I can make edits

**Comment by edwardsarah** [comment]
Added new [slide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g13dcfa1ba5a_0_7) on finding your counterpart on a project(specifically a project's PM) when the website is out of date. Also fixed the screenshots on the slides about checking a project's slack files, so they are in light mode instead of dark mode.

**Comment by edwardsarah** [comment]
https://github.com/hackforla/guides/issues/105#issuecomment-1200589465 Updated action items for gather examples presentation

**Comment by edwardsarah** [comment]
Progress: made almost all of the remaining edits on the gather examples presentation. I'm hoping we can discuss whether it makes sense to have a section dedicated to how examples should be documented v. keeping each slide on documentation in its method section.
Blockers: Table of contents can't be updated until we're solid on all of the slides and have no more edits.

**Comment by edwardsarah** [comment]
Progress: Spent more time going through the presentation and trying to figure out what we could reasonably cut down to make it a more reasonable length. Notes here: https://github.com/hackforla/guides/issues/105#issuecomment-1207495696 
Blockers: If we can discuss as a team what the constraints on the presentation are and what the most important things we feel need to be included are, I can make more edits this week.

**Comment by edwardsarah** [comment]
Progress: Updated table of contents and made suggestions on how to break the presentation into smaller slide decks. https://github.com/hackforla/guides/issues/105#issuecomment-1214198833
Blockers: couldn't remember what other examples we wanted for the slide on example responses.

**Comment by edwardsarah** [comment]
Progress: Reviewed the different gather examples presentations and made edits to parts 4 & 5 to match the formatting of parts 1-3. I think the presentations should be done at this point, but we can review the 5 and decide if there are any further steps to take. 
Haven't heard back from Feyi or Deborah on slack about their linkedin profiles (for the contributors page), so I will reach out via email. Also reviewing the current examples for my guide issue to prep for interviewing other teams. 
Blockers: none currently

**Comment by edwardsarah** [comment]
Progress: had some unexpected family issues come up this week, so I haven't made much progress since monday. My aim right now is to finish up reaching out to teams this week. 
Not related to my particular issue, but I'm curious how many of the other 'in progress' issues on our project board are still actually in progress and if there are any steps we can take on those while we're waiting for review from Bonnie.
Availability: I am out of town starting next Tuesday until the 9th of september. I will aim make more progress on my guide issue but will likely be unable to attend meetings during that time.
