### ISSUE TITLE
Create Document templates for our team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#152]
### Overview
We need document templates so that every time we create a new document it is branded with the project's logo and all documents have a standardized look and feel.

### Action Items
- [x] Copy the documents from other projects (internship has the best documents)
- [x] Copy any assets from Figma
- [x] Customize Figma assets
- [x] Create the following documents in the Document Templates folder
   - [x] Letter Head
   - [x] Report Template
      - [x] Release the dependency on #142
   - [x] Form Template
   - [x] Spreadsheet Template
   - [x] Presentation Template

### Resources/Instructions
- [Guides Google Drive, Document Templates folder](https://drive.google.com/drive/folders/1q9uRtOA_2_Dzh20Z9TTCA-jVg0uWhESy)
- [TWE: Internship template and other graphic asset pages](https://github.com/hackforla/internship/wiki/Design-Process-Overview)
- [Internship Figma, Document templates](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2-35&mode=design&t=SNAwNjeHecUL9O09-0)
- [Guide Figma, Document Templates](https://www.figma.com/file/Jz8KoGTBIxdx9jRxBWrEsF/Guides-Team-Figma?type=design&node-id=1-8&mode=design&t=kPcdHtbncgSXTLwA-0)

**Comment by ExperimentsInHonesty** [comment]
@edwardsarah Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by edwardsarah** [comment]
Alternative document templates to the right-hand side here: https://www.figma.com/file/Jz8KoGTBIxdx9jRxBWrEsF/Guides-Team-Figma?type=design&node-id=1-8&mode=design&t=WZCnZ1r6aUrPJTgk-0

**Comment by edwardsarah** [comment]
@ExperimentsInHonesty Below are copies of the Guides: Report: Template using the two blues we picked as our top choices for the document templates. Please print both versions and reply in a comment to let me know which one you'd like to move forward with. 
[Guides: Report Template v1](https://docs.google.com/document/d/1OOx4Jq15Hfbum7fegxWRqSwGZbet0-Lq21gRi_o4xQ0/edit?usp=sharing)
[Guides: Report Template v2](https://docs.google.com/document/d/1k53Rut2QKrOZqJzwOSXOTp8gF9Puwpv183XuvYRTkTA/edit?usp=sharing)

**Comment by edwardsarah** [comment]
Figma + document templates updated with the dark blue color we decided on.
