### ISSUE TITLE
Research Document Template: Research Plan

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#157]
### Overview
We need to create a Guides team document template for Research Plans based on the Internship team's research document templates.

### Action Items
- [x] Make a new document from Resource 1.01
- [x] Move document to Resource 1.02
- [x] Copy the content from the internship template (Resource 1.03) to the document you just made
- [x] Edit the text to match the type styles for the Guides team (ex. proper fonts and sizes for Headings, body text)
- [x] Add the document to the resources below at 2.01
- [x] Edit the content to be appropriate for the Guides team
- [x] Add the document to the UX Research Guides Templates wiki page (Resource 1.04)
- [x] Delete the example document on the wiki page
#### Resources for creating this issue
1.01 [Guides: Template: Report Template](https://docs.google.com/document/d/1o6NwBRLbFqOZQ8mo6qNOA-HnwdFRuEPurcfnsAZ3--k/edit?usp=sharing)
1.02 [Guides Team - Research Templates](https://drive.google.com/drive/folders/1Q7-A8TG1tU0U6N795rIQa1y3Q6pJ-xCw?usp=drive_link)
1.03 [TWE: Template: Research Plan](https://docs.google.com/document/d/1SDW6n086PnSrrVSmPgQZWhlkz5_yC70vDvp7Lx7u0Wo/)
1.04 [Guides: UX Research Guides Templates](https://github.com/hackforla/guides/wiki/UX-Research-Guides-Templates)

#### Resources gathered during the completion of this issue
2.01 [Guides: Template: Research plan](https://docs.google.com/document/d/1I28sKoaplbqHd_2B6KeXRs5IRC9KcQ9ukVC_wUbQua0/edit?usp=sharing)

**Comment by the-techgurl** [comment]
Hi @edwardsarah I'm done with this issue and it's ready to be looked at on Friday
