### ISSUE TITLE
Research Document Template: How to Use the Research Plan

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/guides#158]
### Overview
We need to create a Guides team document template based on the Internship team's research document templates.

### Action Items
- [x] Make a new document from Resource 1.01
- [x] Rename the document to be Guides: Template: [Name of Document Type]
- [x] Move document to Resource 1.02
- [x] Copy the content from the internship template (Resource 1.03) to the document you just made
- [x] Update content in footers
- [x] Edit the text to match the type styles for the Guides team (ex. proper fonts and sizes for Headings, body text)
- [x] Add the document to the resources below at 2.01
- [x] Edit the content to be appropriate for the Guides team
- [x] Add the document to the UX Research Guides Templates wiki page (Resource 1.04)
- [x] Delete the example document on the wiki page
#### Resources for creating this issue
1.01 [Guides: Template: Report Template](https://docs.google.com/document/d/1o6NwBRLbFqOZQ8mo6qNOA-HnwdFRuEPurcfnsAZ3--k/edit?usp=sharing)
1.02 [Guides Team - Research Templates](https://drive.google.com/drive/folders/1Q7-A8TG1tU0U6N795rIQa1y3Q6pJ-xCw?usp=drive_link)
1.03 [TWE: How to use the Research Plan template](https://docs.google.com/document/d/1Cwc0w4ZPUI8989w3jU8BW2LzLK_Tl5gHdI0VxN5ej0o/)
1.04 [Guides: UX Research Guides Templates](https://github.com/hackforla/guides/wiki/UX-Research-Guides-Templates)
#### Resources gathered during the completion of this issue
2.01 [Guides: How to Write a Research Plan](https://docs.google.com/document/d/1HSkZoetI4rxa-w4-GWhm5CAR9FxMzVnZf4vILYHrYic/edit?usp=sharing)

**Comment by edwardsarah** [comment]
Hey @the-techgurl, were you able to make any progress this week working on this template? I know you said you were dealing with blackouts, so no worries if not.

**Comment by the-techgurl** [comment]
Hi @edwardsarah unfortunately I wasn't able to

**Comment by edwardsarah** [comment]
Ready for Review on 2/2
