### ISSUE TITLE
Cleanup Guide template: Typography Effective Practices #48

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#19]
### Overview
We need to cleanup this create a guide issue so that it has the current structure of guide issues.

### Action Items
- [x] Make a copy of the current top of the issue and put it in a comment below so that we can keep it if we need to retrieve any of the prior content. 
  - [x] Add a copy of link to the resources, and then hide the comment
- [x] Take guide template from the related community of practice and insert it into the current guide issue, keeping all the existing content if relevant

### Resources/Instructions
- Related Community of Practice: UI/UX
- Guide issue: https://github.com/hackforla/UI-UX/issues/48
- Link to Guide: ?
- comments from Hana and Danielle: https://github.com/hackforla/design-systems/issues/53#issuecomment-900699573

**Comment by ExperimentsInHonesty** [comment]
Will ask Hana about this again https://github.com/hackforla/design-systems/issues/117#issuecomment-927945061

**Comment by ExperimentsInHonesty** [comment]
Transferred issue to Design System repo 
The typography issue formerly ui/us issue 48 has been transferred and is now https://github.com/hackforla/design-systems/issues/137

**Comment by SheIsBukki** [comment]
Tracker Updated
