### ISSUE TITLE
Cleanup Guide template: Designers Toolkit #25

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#22]
### Overview
We need to cleanup this create a guide issue so that it has the current structure of guide issues.

### Action Items
- [x] Add note from Danielle and Hana
- [ ] Update tracker
- [ ] Close this issue

### Resources/Instructions
- Related Community of Practice: UI/UX
- Guide issue: https://github.com/hackforla/UI-UX/issues/25
- Link to Guide: ?
- comments from Hana and Danielle: https://github.com/hackforla/design-systems/issues/53#issuecomment-900699573

**Comment by ExperimentsInHonesty** [comment]
I have cleaned up this guide.  The remaining item is to make sure its up to date in the tracker.

**Comment by SheIsBukki** [comment]
Updated on Tracker
