### ISSUE TITLE
Cleanup Guide template:Defining Hack for LA identity #1

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#23]
### Overview
We need to cleanup this issue so that it has the current structure of guide issues.

### Action Items
- [x] Review issue and identify next steps
- [x] Write to assigned person asking them why its on hold
- [x] Check reply
- [x] Annotate issue 
- [x] Move the issue to icebox

### Resources/Instructions
- Related Community of Practice: UI/UX
- Guide issue: https://github.com/hackforla/UI-UX/issues/1
- Link to Guide: ?
- comments from Hana and Danielle: https://github.com/hackforla/design-systems/issues/53#issuecomment-900699573
- [Product Template for writing a new guide issue](https://github.com/hackforla/product-management/issues/new?assignees=&labels=TG%3A+Gather+Examples%2C+documentation%2C+feature%3A+guide+creation&template=template-for-making-guides-templates.md&title=Create+a+Guide%2FTemplate%3A+%5Bname+of+item%5D+for+your+project)

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/UI-UX/issues/1

**Comment by SheIsBukki** [comment]
Updated on Tracker
