### ISSUE TITLE
Cleanup Guide template: Website Style Guide and Design System #24

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#24]
### Dependency
Bonnie and Hana meeting on Monday at 1pm
"Answer Please show me what you are creating at our next meeting (2021-08-30)"

### Overview
We need to cleanup this create a guide issue so that it has the current structure of guide issues.

### Action Items
- [ ] Make a copy of the current top of the issue and put it in a comment below so that we can keep it if we need to retrieve any of the prior content. 
  - [ ] Add a copy of link to the resources, and then hide the comment
- [ ] Take guide template from the related community of practice and insert it into the current guide issue, keeping all the existing content if relevant

### Resources/Instructions
- Related Community of Practice: Product Management 
- Guide issue: https://github.com/hackforla/product-management/issues/24
- Link to Guide: ?
- comments from Hana and Danielle: https://github.com/hackforla/design-systems/issues/53#issuecomment-900699573

**Comment by ExperimentsInHonesty** [comment]
@SheIsBukki please update tracker

**Comment by ExperimentsInHonesty** [comment]
@SheIsBukki updated the tracker to indicate issue is closed and replaced.
