### ISSUE TITLE
Cleanup Guide template: Terms and Conditions for your project #114

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#27]
### Overview
We need to cleanup this create a guide issue so that it has the current structure of guide issues.

### Action Items
- [x] Make a copy of the current top of the issue and put it in a comment below so that we can keep it if we need to retrieve any of the prior content. 
- [x] Take guide template from the related community of practice and insert it into the current guide issue, 
  - [x] Add a ink to the comment with the prior text, to the resources section,
  - [ ] Copy relevant portions in to above section
  - [ ] then hide the comment

### Resources/Instructions
- Related Community of Practice: Product Management 
- Guide issue: https://github.com/hackforla/product-management/issues/114
- Link to Guide: ?
- comments from Hana and Danielle: https://github.com/hackforla/design-systems/issues/53#issuecomment-900699573

**Comment by ExperimentsInHonesty** [comment]
update the tracker.  This has been moved to the draft template stage.

**Comment by SheIsBukki** [comment]
Tracker updated
