### ISSUE TITLE
Agendas and Transcripts of meetings

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#3]
### Overview
This issue will hold transcripts and recordings for meetings so that we can refer back to them if necessary.

### Action Items
- [ ] Record meeting and turn on transcript
- [ ] Upload recordings.  Can only be done by Bonnie (they are on her machine)
- [ ] Add Transcript of the meeting to the Resources section 
- [ ] Add Recording of the meeting to the Resources section

### Resources/Instructions
[All recordings](https://drive.google.com/drive/folders/1M643laq00Yvm8SaeacYRf8WWxVTWmoJf?usp=sharing)
- 07/15/21 - setting up github repo, making teams, adding people to teams, setup project board and write a few issues and do initial assignments
  - [07/15/21 meeting_saved_closed_caption.txt](https://github.com/hackforla/guides/files/6824595/meeting_saved_closed_caption.txt)
  - [07/15/21 video](https://drive.google.com/file/d/1u7ijH0yvpGPjGtdL_Siv_grIQryHm1my/view?usp=sharing)
- [07/16/21]
   - [Recording](https://drive.google.com/file/d/1aMXqXUslvzEO3tqJfNlH64bfnkOPdWk9/view?usp=sharing)
- [07/19/21 Meeting points](https://github.com/hackforla/guides/issues/3#issuecomment-882628510)
- [07/21/21 Meeting points](https://github.com/hackforla/guides/issues/3#issuecomment-884429327)
- 7/23/21 [Meeting Transcript](https://github.com/hackforla/guides/files/6869767/meeting_saved_closed_caption.txt) | [Meeting points](https://github.com/hackforla/guides/issues/3#issuecomment-885728821)
- [07/26/21](https://github.com/hackforla/guides/issues/3#issuecomment-886947470)
- [07/28/21](https://github.com/hackforla/guides/issues/3#issuecomment-888430535)
- [07/30/21](https://github.com/hackforla/guides/issues/3#issuecomment-889991695)
- [08/04/21](https://github.com/hackforla/guides/issues/3#issuecomment-892783881)
- [08/25/21](https://github.com/hackforla/guides/issues/3#issuecomment-905693155)

**Comment by ExperimentsInHonesty** [comment]
I will add todays recording and transcript

**Comment by ExperimentsInHonesty** [comment]
1. Progress accidentially closed meeting window without saving transcript but can upload recording
2. Blockers: got busy this weekend
3. Availability: Tuesday 20 min
4. ETA: Done by wed

**Comment by gautham-l** [comment]
July 19, 2021, Meeting agenda and points discussed.

Agenda: Get updates on Issue #2 and issue #1 

Points discussed:
1. Build autoresponders under GitHub issue to seek updates from team members through comments. We can also use Bonni's autoresponder template.
2. Provide updates on issues through comments under respective issues.
3. Recap on downloading and uploading files from shared folder to Organization's Google Drive: Hack for LA Guides.
4. Recap on points related to writing a (guide for Adding Members)[https://docs.google.com/document/d/1qMfBWrtwzhzknydWHbqrGwkfbRkNhoCUHWjgjWaePe0/edit?usp=drive_web&ouid=113215052388734356505] to Organization's Google Drive: Hack for LA Guides.
5. Created an (audit spreadsheet)[https://docs.google.com/spreadsheets/d/1mO3MPGPs3fD45XI1yuVeToqROS6n4rmY8ciGjVst9sc/edit?usp=sharing] and added topics for Bukki to complete her audit.
6. How to add document links pertaining to the issue as resources under description rather than adding them as comments.

**Comment by gautham-l** [comment]
July 22, 2021 (Wednesday), Meeting agenda and points discussed.

**Agenda**: Review tasks completed on issues #1 and #2 

**Points discussed**:
1. How to find CoP Leads - through hackforla [website](https://www.hackforla.org/communities-of-practice) and Community of Practice [respository](https://github.com/hackforla/communities-of-practice).
2. How to check dependency tasks and their progress.
3. How to view all issues assigned to you from all the organizations joined under GitHub.
4. Regarding #1, Olivia is already creating a guide for CoP leads to migrate to the organization's official shared drive. Gautham may review and update Olivia on the points discussed with Bonnie.
5. Issue #7 was created for Bonnie to add a shared drive for the Community of Practice repository and roster.
6. All guides pertaining to Guides Project/Repository must be stored under [GUIDES TEAM FOLDER](https://drive.google.com/drive/folders/1vn6FIh-ivNXCqePHgikhMC_6i0hFqMZr?usp=sharing).
7. Reviewed #2, Bonnie provided suggestions and helped Bukki to progress with the audit.
8. Issue #6 was created for project readme.md referring this [issue](https://github.com/hackforla/open-community-survey/issues/7).
9. Issue #8 was created for project one-sheet referring this [issue](https://github.com/hackforla/GreenEarthOS/issues/1).
10. Gautham has to remind Bonnie to start recording on every Zoom meeting regarding Guides project.

**Comment by ExperimentsInHonesty** [comment]
7/23/21

Transcript
[meeting_saved_closed_caption.txt](https://github.com/hackforla/guides/files/6869767/meeting_saved_closed_caption.txt)

**Comment by gautham-l** [comment]
July 23, 2021 Meeting points.

Buki,
1. Create ReadMe.
2. Update Audit excel sheet for the Product Management team and Feature label column.

Gautham,
1. Create a roster for CoP leads.
2. Give CoP leads access to shared drive.

**Comment by ExperimentsInHonesty** [comment]
July 26, 2021 

[Recording](https://drive.google.com/file/d/1AC38aO4hIZxrhraNmTQq_a6y65LXITTe/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
July 16, 2021 (out of order from the other comments, because I just found the recording)

**Comment by ExperimentsInHonesty** [comment]
[meeting_saved_closed_caption.txt](https://github.com/hackforla/guides/files/6894715/meeting_saved_closed_caption.txt)

**Comment by ExperimentsInHonesty** [comment]
[meeting_saved_closed_caption.txt](https://github.com/hackforla/guides/files/6908746/meeting_saved_closed_caption.txt)

**Comment by ExperimentsInHonesty** [comment]
8/4/21 [meeting_saved_closed_caption.txt](https://github.com/hackforla/guides/files/6932700/meeting_saved_closed_caption.txt)

**Comment by ExperimentsInHonesty** [comment]
8/11/21 
[closed_caption.txt](https://github.com/hackforla/guides/files/6970246/closed_caption.txt)

**Comment by ExperimentsInHonesty** [comment]
All the recordings though 8/16 have been uploaded, next steps are to annotate this issue with the appropriate links.  If you need the recording/transcripts s in the meantime, check the folder listed above.

**Comment by carolzjy** [comment]
[meeting_saved_closed_caption.txt](https://github.com/hackforla/guides/files/7048508/meeting_saved_closed_caption.txt)

**Comment by ExperimentsInHonesty** [comment]
We have decided to stop recording the meetings around the 20th (I think).  I will upload the rest of the recordings when I get time.

**Comment by ExperimentsInHonesty** [comment]
Add to next team meeting agenda
- This needs an update https://www.hackforla.org/projects/guides-team

**Comment by ExperimentsInHonesty** [comment]
### Task items
- We need to revise this agenda issue to be more like https://github.com/hackforla/open-community-survey/issues/68
v

### Team updates
- Bukki identified that this issue https://github.com/hackforla/product-management/issues/153 did not have a link to the draft.  It is in the old pm folder.  We linked it in the issue
- Bukki identified that this issue was ready for a leadership review https://github.com/hackforla/product-management/issues/33.  We made notes and are sending back to him for one more addition.
