### ISSUE TITLE
Cleanup Guide template: Template for making composite images in our HfLA guides #55

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#31]
### Overview
We need to cleanup this create a guide issue so that it has the current structure of guide issues.

### Action Items
- [x] Make a copy of the current top of the issue and put it in a comment below so that we can keep it if we need to retrieve any of the prior content. 
  - [x] Add a copy of link to the resources, and then hide the comment
- [x] Take guide template from the related community of practice and insert it into the current guide issue, keeping all the existing content if relevant
- [ ] Make sure the status of the template is updated on the tracker https://github.com/hackforla/UI-UX/issues/55

### Resources/Instructions
- Related Community of Practice: UI/UX
- Template issue: https://github.com/hackforla/UI-UX/issues/55
- Related Guide issue: https://github.com/hackforla/UI-UX/issues/92 (this guide uses the template)
- Link to [Guide Doc](https://docs.google.com/document/d/1OyPfKqUU7ZinhjMoRmsXywyZfME_Oo_hpC2Zdxlb310/edit#)
- Link to [Template](https://docs.google.com/presentation/d/1xu_lYuucKkBKD9jWfLDZkEv3PkmIjcFEf0MnjEJdV5c/edit#slide=id.gcd84038bdd_0_0)

**Comment by ExperimentsInHonesty** [comment]
Make sure the status of the template is updated on the tracker https://github.com/hackforla/UI-UX/issues/55

**Comment by SheIsBukki** [comment]
Updated on Tracker
