### ISSUE TITLE
Cleanup Guide template: making a press release for your open source project #8

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#34]
### Overview
We need to cleanup this create a guide issue so that it has the current structure of guide issues.

### Action Items
- [x] Make a copy of the current top of the issue and put it in a comment below so that we can keep it if we need to retrieve any of the prior content. 
  - [x] Add a copy of link to the resources, and then hide the comment
- [x] Take guide template from the related community of practice and insert it into the current guide issue, keeping all the existing content if relevant
- [ ] Add the labels this repo needs in order to classify guides.

### Resources/Instructions
- Related Community of Practice: Marketing
- Guide issue: https://github.com/hackforla/knowledgebase-content/issues/119
- Link to Guide: https://github.com/100Automations/Website/issues/158#issuecomment-794527683

**Comment by ExperimentsInHonesty** [comment]
the restructure has been completed  - its in the prioritized backlog
