### ISSUE TITLE
Create a project card for Guides on Hack for LA website 

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#38]
### Dependency
~Create logo & hero https://github.com/hackforla/guides/issues/39~

### Overview
We need to have a project card on the hack for LA website, so that we can recruit new team members

### Action Items
- [x] Gather items for project card
  - [x] logo on an image 600x400
  - [x] hero image 1500x700
  - [x] one sheet url (called overview on project card) #8 
- [x] Add the content to https://github.com/hackforla/website/issues/2289 
   - [x] Ask Bonnie to remove the dependency and put the issue into the prioritized backlog on hackforla website repo
   - [x] Check to see progress on the issue

### Resources/Instructions
- ~[Website's team Issue for adding guides team card](https://github.com/hackforla/website/issues/2289)~
- https://github.com/hackforla/website/issues/2462
- [HackForLA](https://www.hackforla.org)
- [Guides Project Profile page](https://www.hackforla.org/projects/guides-team)

**Comment by ExperimentsInHonesty** [comment]
Logo and hero
600 x 400
Alt text: 'Globe Map made of dots and hackforla logo and text reading Guides Team'
![guides-team](https://user-images.githubusercontent.com/37763229/134694971-836863d6-f445-4b8f-9d28-6974867f86e2.jpg)

1500x700 
![guides-team-hero](https://user-images.githubusercontent.com/37763229/134694967-fb336994-8eea-46f8-8136-7dd8e6109cb5.jpg)

**Comment by ExperimentsInHonesty** [comment]
Overview URL: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Guides-Team-One-Sheet.pdf

**Comment by ExperimentsInHonesty** [comment]
Has not been assigned yet

**Comment by ExperimentsInHonesty** [comment]
No one has responded to the slack message.  Bring up on Sunday at the team meeting.

**Comment by ExperimentsInHonesty** [comment]
We need to identify who is working on our project and provide that information to the website team using this format
leadership:
```
  - name: First Last
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/xxxxxx'
      github: 'https://github.com/githubusername'
```
- name: Bonnie Wolfe
   role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/UE1UG1YFP'
      github: 'https://github.com/experimentsinhonesty'

**Comment by carolzjy** [comment]
- name: Carol Zhu
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/UVA3VD727'
      github: 'https://github.com/carolzjy'

**Comment by SheIsBukki** [comment]
- name: Bukola Ogunleye
   role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U02617GM7QX'
      github: 'https://github.com/SheIsBukki'

**Comment by thuyhle193** [comment]
- name: Thuy Le
role: Product Manager
links:
slack:U02GGGF26D9
github:https://github.com/thuyhle193

-

**Comment by ExperimentsInHonesty** [comment]
opened a new issue https://github.com/hackforla/website/issues/2462 to add team members

**Comment by ExperimentsInHonesty** [comment]
Check it on 2021-12-01

**Comment by SheIsBukki** [comment]
These are the items that are currently missing from the project card
- Tools: Google Docs, Google Drive, Figma, GitHub Wiki, GitHub
- Program Areas: Civic Tech Infrastructure

**Comment by ExperimentsInHonesty** [comment]
These are the people to remove
Carol Zhu
Thuy Le

**Comment by ExperimentsInHonesty** [comment]
Please create a [new issue on the website repo](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D) for updating our project card

**Comment by SheIsBukki** [comment]
##Update
In reference to this https://github.com/hackforla/guides/issues/38#issuecomment-1048993281, I have created the issue https://github.com/hackforla/website/issues/2888

**Comment by SheIsBukki** [comment]
@ExperimentsInHonesty I assume that this issue is done?
