### ISSUE TITLE
Make Issues for CoP Audits

### ISSUE THREAD

**Issue by carolzjy** [hackforla/guides#48]
### Overview
We need to make an issue for auditing each CoP's publication labels

### Action Items
- [x] Make issues for each CoP
- [x] Add milestone
- [x] Drag into prioritized backlog based on milestone

### Resources/Instructions
- [x] UI/UX #37 
- [x] Product Management #47 
- [x] Data Science #49 
- [x] Marketing #50 
- [x] Revenue #51 
- [x] Dev Ops #52 
- [x] Engineering #53

**Comment by ExperimentsInHonesty** [comment]
We are moving all the guide issues and their documents to a central location which will be accessible from a single project board
- Repo: [knowledgebase content repo](https://github.com/hackforla/knowledgebase-content)
- Google Drive: [Knowledgebase-content](https://drive.google.com/drive/folders/1QJRmMahd8jWOdVOMEW9VDI-qowFlQwV2?usp=drive_link)
- Project Board: [Guides: Knowledgebase Content Tracker](https://github.com/orgs/hackforla/projects/40)


And here is our guide for doing that move.

- Guide: [How to Move a Guide to a New Repo](https://docs.google.com/document/d/1y6uQUKRSwuJPdfwX_jWbOXWYRuBja9YGNbF3OEsjjOA/edit?usp=sharing)
