### ISSUE TITLE
Onboarding: Emmanuel

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#78]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

### Action Items
- [ ] Add to the notes document as you go with any observations, no matter how small.
- [ ] Review the Presentation for Gathering Examples
- [x] Pick a guide 
- [ ] Use the presentation to work on the guide
- [ ] Clean up the notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- [Emmanuel' s Notes](https://docs.google.com/document/d/1k8iLlJ4bUrHBNWVqDzXh_rBneE46w4kVeh9MnHjm7pI/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@kingojem Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by kingojem** [comment]
1. Progress
       - Guide Picked:
           > https://github.com/hackforla/product-management/issues/23
2. Blockers
     - There isnt a way to ascertain the completion of a form

**Comment by ExperimentsInHonesty** [comment]
Didn't come to meeting on Wednesday 2022-01-26 or drop us a line in the channel.  Hopefully we will hear from him on Monday

**Comment by ExperimentsInHonesty** [comment]
@kingojem Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
We have not heard from you via this issue or slack for 3 full weeks.  We are going to remove you from the team resources  You are welcome to come back, when you are ready, you can message us in the [#guide](https://hackforla.slack.com/archives/C028T9XU9S5) Slack channel to be re-added.
