### ISSUE TITLE
One-Sheet for Guides Project

### ISSUE THREAD

**Issue by gautham-l** [hackforla/guides#8]
### Dependency
Logo issue #39 

### Overview
As a Project Lead, I want a one-sheet for the guides project including milestones for the next 6 months so that we can recruit more members and speed up guides automation.

### Action Items
- [x] Refer Civic Opportunity one-sheet.
- [x] Refer one more one-sheet example.
- [x] Create first draft of one-sheet.
- [x] Add one-sheet draft as link under Resources/Instructions section below.
- [x] Prepare questions for review.
- [x] Review the one-sheet draft with Bonnie.
- [x] add logo
- [x] create pdf
- [x] upload pdf to Finished one sheets location (see resources below)
- [x] add url of pdf to #38 

### Resources/Instructions
- [Civic Opportunity one-sheet](https://github.com/hackforla/civic-opportunity/blob/master/Civic_Opportunity_Project_OnePage.pdf)
- [One-sheet examples](https://github.com/hackforla/product-managment/issues/3)
- [Finished one sheets](https://github.com/hackforla/product-management/tree/master/project-one-sheets)

[Guides one sheet](https://docs.google.com/document/d/1P8yaO-ICkRflqiTrrJ4wMFAIlowk-a7TBATtxRTUb2Q/edit?usp=sharing)
[PDF of one sheet in our google drive](https://drive.google.com/file/d/16BYKgvgCU_ckXUJKG-LsCt2eWCPQVxZZ/view?usp=sharing)
[Location of Guides Team one sheet on the Product Management repo](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Guides-Team-One-Sheet.pdf)

Check this issue later to see if the template has been reverted to its original https://docs.google.com/document/d/1BCNkA3cEox1qp2803r1uDAtffEszQ2P34ZDHo4dKM0Y/edit#heading=h.n7lqzt5pn161

[Folder with one sheet assets in it](https://drive.google.com/drive/folders/1vVQFcTdLurbPoMNmuagJIzKn3Muuz2gV?usp=sharing_)

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by carolzjy** [comment]
I have been working on a draft. The recent improvements/progress section is taking longer than expected. I'm actively working on it and should be able to finish it by Friday EOD.

**Comment by ExperimentsInHonesty** [comment]
@carolzjy please add a link to the draft in the issue

**Comment by carolzjy** [comment]
https://docs.google.com/document/d/1P8yaO-ICkRflqiTrrJ4wMFAIlowk-a7TBATtxRTUb2Q/edit

**Comment by ExperimentsInHonesty** [comment]
We finished with all the text, only adding the logo remains.  Once logo has been added next steps are above

**Comment by ExperimentsInHonesty** [comment]
we have completed
