### ISSUE TITLE
Onboarding: Olumuyiwa

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#81]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  So any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.

### Action Items
- [x] Create a google doc, with the name ```GT: Notes on Gather presentation - OLUMUYIWA``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [x] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: 
- Guide you are working on
   - Name of guide: Communication (style) Guide for Document Creation #278
   - URL of guide Issue: github.com/https://github.com/hackforla/product-management/issues/278

**Comment by olubabzy** [comment]
Communication (style) Guide for Document Creation #278
 github.com/hackforla/product-management/issues/278

**Comment by olubabzy** [comment]
@ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
Sent message in Slack with link to previous comment

**Comment by ExperimentsInHonesty** [comment]
sent another message on slack

> Olumuyiwa Babalola If you want to remain on the team, please provide an update on your issue https://github.com/hackforla/guides/issues/81#issuecomment-1041862380

**Comment by SheIsBukki** [comment]
@olubabzy reached out on Slack 
Hello Bukki, Good morning
[02/25/2022](https://hackforla.slack.com/archives/D030QFELLE5/p1645786765039939)
Pls, help me talk to Bonnie, she sent me a message that I will be off the team if I don't give an update on my task. I have been sick since last week, and I am yet to recover. I haven't been able to access my laptop. By Monday by God's grace, I will be back.

**Comment by ExperimentsInHonesty** [comment]
@olubabzy Sending you our prayers for a good recovery.  We will check on you on 2022-03-30

**Comment by SheIsBukki** [comment]
We offboarded Olumuyiwa
