### ISSUE TITLE
Onboarding: TOLULOPE ADEKOJO

### ISSUE THREAD

**Issue by Toluadekojo** [hackforla/guides#83]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  So any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.

### Action Items
- [x] Create a google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [x] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather Presentation-Tolulope Adekojo](https://docs.google.com/document/d/1JaKuh3XQUWUOR2_BHonPoUDTXWU7IZ1ZILXkyqjKZAI/edit)
- Guide you are working on
   - Name of guide: Create a Guide/Template:PM Terminologies
   - [URL of guide Issue](https://github.com/hackforla/product-management/issues/314)

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
Toluope would have written for the update
1. Progress: I have started the notes doc and added some suggestions to it, those are ready to be reviewed
2. Blockers: none
3. ...

**Comment by ExperimentsInHonesty** [comment]
In today's meeting, we reviewed all the current suggestions from the doc and updated the deck with changes and comments for future changes.

**Comment by Toluadekojo** [comment]
Please provide update
1. Progress: My notes have been reviewed. I need to go through the presentation again for some more observations.
2. Blockers: Personal reasons. I also need more explanation on what my presentation to the team entails. (The 10th task)
3. Availability: 4hours
4. ETA: 28-2-2022
5. Pictures (if necessary): None.

**Comment by Toluadekojo** [comment]
Please provide update

1. Progress: I cleaned up my note and I am ready to present my observations to the team.
2. Blockers: None
3. Availability: 4 hours
4. ETA: 28-2-2022
5. Pictures (if necessary): None.

**Comment by ExperimentsInHonesty** [comment]
Next steps are to use the [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit) to work on the 
[Create a Guide/Template:PM Terminologies](https://github.com/hackforla/product-management/issues/314)

**Comment by Toluadekojo** [comment]
Progress: None from the last time
Blockers: Personal, I have been ill.
Availability: Not sure, depends on my recovery 
ETA: 4-4-2022
Pictures (if necessary):

**Comment by ExperimentsInHonesty** [comment]
@Toluadekojo checking back in on you. Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Toluadekojo It's been a month 
Please let us know if you will be returning.  

Check on them next week, send week 2 message

**Comment by ExperimentsInHonesty** [comment]
@Toluadekojo is it the amount of time required per week, or when the team meets?

**Comment by ExperimentsInHonesty** [comment]
@Toluadekojo is it the amount of time required per week, or when the team meets?

> Hello Bonnie,
> I apologize for the silence. I dropped a message a while ago on Slack and I assumed that would suffice. I am currently swamped with work and I am not sure I can't get through with my tasks on here within the stipulated timeframe.
> 
> I really would still like to be on the team but I don't know how possible that is with my current work schedule.

**Comment by ExperimentsInHonesty** [comment]
@Toluadekojo is it the amount of time required per week, or when the team meets?

> Hello Bonnie,
> I apologize for the silence. I dropped a message a while ago on Slack and I assumed that would suffice. I am currently swamped with work and I am not sure I can't get through with my tasks on here within the stipulated timeframe.
> 
> I really would still like to be on the team but I don't know how possible that is with my current work schedule.

**Comment by ExperimentsInHonesty** [comment]
If we don't hear from her by 2022-04-29, remove from team.

**Comment by SheIsBukki** [comment]
> Hello Bonnie, I apologize for the silence. I dropped a message a while ago on Slack and I assumed that would suffice. I am currently swamped with work and I am not sure I can't get through with my tasks on here within the stipulated timeframe.
> 
> I really would still like to be on the team but I don't know how possible that is with my current work schedule.

@Toluadekojo Being present during meetings is great but you don't have to come for all meetings. You can work on issues and provide regular updates so that we can see your progress and help if/when you have any blockers.

**Comment by ExperimentsInHonesty** [comment]
@Toluadekojo Thanks for letting us know.  We will remove you from the team.  You can message us in the slack when you want to rejoin.
