### ISSUE TITLE
Onboarding: Olatunji

### ISSUE THREAD

**Issue by Headies** [hackforla/guides#84]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  So any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.

### Action Items
- [x] Create a google doc, with the name ```GT: Notes on Gather presentation - Olatunji Lawal``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [Olatunji Lawal](https://docs.google.com/document/d/1fTMmOpkHMhW-ADP2xQGK6k1aAWFMps9Q9AiQIwo6Dkk/edit)
- Guide you are working on
   - Name of guide - Presentation deck for your project #183
   -  [URL of guide Issue](https://github.com/hackforla/product-management/issues/183)

**Comment by Headies** [comment]
1. Progress: 
i. Created a document and picked a guides to work on. 
ii. Moved the assigned guides to "in progress"
2. Blockers: personal for now and making observations for further clarity. 
3. Availability: 2hours
4. ETA: Wednesday 
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Headies** [comment]
Progress: added my observation to my google doc
ETA: Monday
Blockers: personal reasons

**Comment by Headies** [comment]
Progress: Observations documented and ready to be reviewed

**Comment by ExperimentsInHonesty** [comment]
@Headies Thanks for the response.  I am not exactly clear on how to handle the issue.  Are we talking a week break, or month, etc?  Can you give us an ETA on the break, so I know the next action to take.

**Comment by Headies** [comment]
A week break. I will be back to the team on the 29th of this month.

**Comment by ExperimentsInHonesty** [comment]
Check back in on them on 2022-04-30

**Comment by ExperimentsInHonesty** [comment]
@Headies 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Headies 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

Next message to be sent on 2022-04-12

**Comment by ExperimentsInHonesty** [comment]
@Headies We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by Headies** [comment]
Hi Bonnie,

Sorry, I have not responded in weeks.

I have been swamped with work and the meeting schedule clashes with my work hours.

I'd hope to be back on the team in no time.

Regards

**Comment by ExperimentsInHonesty** [comment]
@Headies Its been over a month.  I was really clear during onboarding that if you don't have the time to volunteer at Hack for LA (minimum 6 hours a week) then you should not volunteer here.  So while I understand not being able to make this meeting time.  You could be working on the issue asynchronously, but you are not doing that either.  It's using up time every meeting to check on you and your issue. I am going to remove you from the team.  If you want to join us again, please reach out in the team Slack channel when you have time.
