### ISSUE TITLE
Onboarding: AGBO IVEREN

### ISSUE THREAD

**Issue by Evon081** [hackforla/guides#85]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  So any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.

### Action Items
- [x] Create a google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [x] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather Presentation - IVEREN AGBO](https://docs.google.com/document/d/1juuHa4qlv2D1Ik-TdsOGKwZvLfnOq3vGzalNrxusQAk/edit)
- Guide you are working on
   - Name of guide : Managing your project's slack channel
   - URL of guide Issue : https://github.com/hackforla/product-management/issues/50

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Evon081** [comment]
Yes I am still on the team . 
I have been having health challenges. 

I would be back next week with update on the issue. 
Thank you .

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Sorry to hear you have not been feeling well. Thank you for the update.  We look forward to seeing you next week.

**Comment by Evon081** [comment]
> Please provide update
> 
> 1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
> 2. Blockers: "Difficulties or errors encountered."
> 3. Availability: "How much time will you have this week to work on this issue?"
> 4. ETA: "When do you expect this issue to be completed?"
> 5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

1. I have been able to complete 3 tasks amongst the 10 in this issue.
2. I only had a little difficulty understanding the gather example presentation.
3.  I have as much time as i need.
4. I expect this issue to be completed on Friday, 4th of march 2022.
5. none yet

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
Please share the details about what you are find in your issue by annotating the issue, if you find that they have the practice or don't.  Also think about how we might inform or improve the Slides for gathering examples to make it clear to guide creators what we expect them to do in the Gather examples phase.

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
Left my update in the issue https://github.com/hackforla/product-management/issues/50#issuecomment-1066878305

**Comment by Evon081** [comment]
ISSUE UPDATE
1. Progress: i have completed the gather examples task by gathering examples from the different project slack channels.
2. Blockers: i do not understand the next two task? what is the difference between "create draft template" and " create 
                     guide"?
4. Availability: i am readily available
5. ETA: as soon as any blockers are cleared?
6. Pictures :

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Hi!  Great question. 
> Blockers: i do not understand the next two task? what is the difference between "create draft template" and " create guide"?

The difference is that some guides need a template and a guide and some only need a guide.  Your issue probably only needs a guide.  

An example of an issue that requires a template is the Research Plan issue.  The template is a Google doc with all the sections that need to be covered by a research plan, but no instructions on how to fill out the research plan.  The guide gives you instructions and examples of how others have filled out the template.

- [Guide: HOW TO - WRITE A RESEARCH PLAN ](https://docs.google.com/document/d/1ovSBNVkuizZD2EMOE2w522_x-sOAzQBEheMqfPWmQKk/edit#heading=h.c8tc614ce3iu)
- Research Plan Template [preview](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/preview) | [copy](https://docs.google.com/document/d/1lTmjiAzSwiUOFD4f4eGs0WGktaqZ6ogx_fiXhP7oR9U/copy)

**Comment by Evon081** [comment]
I have  started creating the guide on "HOW TO MANAGE YOUR TEAMS SLACK CHANNEL"

The link below-
https://docs.google.com/document/d/1-1XZiOajQfY1GRiq9f2CnWv3SsJo3iSseI5iO6tCYb8/edit

all i have now is the overview of what a slack channel is and im still putting together the table of content.

**Comment by ExperimentsInHonesty** [comment]
Ivy moved the file into the product management Google Drive, into its own folder in guides.  Ivy will do an update on the issue to communicate that she has finished surveying and recording what she found on all the Slack channels, and will be moving on to reaching out to all the pms to find out what has worked and not worked about their slack management.

**Comment by SheIsBukki** [comment]
@Evon081   Please provide an update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Evon081** [comment]
update:
I have started reaching out to product leads on slack to fix a suitable meeting time for us.
The purpose of this meeting is to have a discussion on the management of their teams slack channel.

i have reached out to about 7 team leads and i have a meeting with  the product manger of the Hack website today.

**Comment by ExperimentsInHonesty** [comment]
@Evon081 
Please provide weekly update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Evon081 put a link to the other issue you are also working on.  And let's figure out what kind of guidance we need to provide to people so that they understand if they made a sub issue, it has to be linked to the main issue.

**Comment by Evon081** [comment]
I have reached out to the team leads of the following projects as regards my issue:
https://github.com/hackforla/product-management/issues/50


VRMS
Open community project
lucky parking
home unite us
ESM triange
TDM calculator
hack website
Engage
Expunge Assist
Civic Tech Structure
Design Systems
Civic Tech Index
Civic Tech Jobs
Brigade Playbook
Civic Opportunity Project
Access the Data
100 automations
311 data

I got the following responses
- The team lead for the Hack website and we are yet to fix a meeting date and time.
- The team lead for Access-the-data, Lucy Chang has agreed for a meet next week tuesday 12-04-2022.
- the team lead for Design Systems, Yasaman, responded but we haven't fix a meeting date
- The team lead for 311 Data, Eric Cho, said he would be available to chat the week of April 18th.
- No response from all other teams.

**Comment by Evon081** [comment]
have reached out to the team leads of the following projects as regards my issue:
https://github.com/hackforla/product-management/issues/50

VRMS
Open community project
lucky parking
home unite us
ESM triange
TDM calculator
hack website
Engage
Expunge Assist
Civic Tech Structure
Design Systems
Civic Tech Index
Civic Tech Jobs
Brigade Playbook
Civic Opportunity Project
Access the Data
100 automations
311 data

I got the following responses

The team lead for the Hack website and we are yet to fix a meeting date and time.
The team lead for Access-the-data, Lucy Chang has agreed for a meet next week tuesday 12-04-2022.
the team lead for Design Systems, Yasaman, responded but we haven't fix a meeting date
The team lead for 311 Data, Eric Cho, said he would be available to chat the week of April 18th.
I am having a chat with the team lead of Expunge Assist, Thomas Demoner, on Tuesday.
No response from all other teams.

**Comment by ExperimentsInHonesty** [comment]
We added a note to the slide "How to Connect with Other Teams" to have a stronger message about reaching out to people via the team's Slack channel vs doing it privately.

Before

> Step 5
> Reach out in the project’s Slack channel of each team, to your counterpart in order to find out if they are still the lead.
> 
> To find your counterpart, check [HackforLA.org](https://hackforla.org/) for the project’s Current Project Team.

After

> Step 5
> Reach out in the project’s Slack channel of each team (it's important not to message them privately at this stage), to your counterpart in order to find out if they are still the lead.
> 
> To find your counterpart, check [HackforLA.org](https://hackforla.org/) for the project’s Current Project Team.

**Comment by Evon081** [comment]
I have redirected my messages from the PM's DM on slack to their channels. 
im positive about getting faster responses now.

I had a meeting with the following PMS
-Yasamaan of Designs systems on the 14th march
-Lucy from Access the data on the 14th march.
however i am yet to annotate my findings. this will be done on or before monday.

**Comment by Evon081** [comment]
Since reaching out to PM's via their teams slack channel, I have had more engagements with them.
i have had meetings with:

-Yasamaan of Designs systems on the 14th march
-Lucy from Access the data on the 14th march.

I have scheduled meetings this week with-
-Danish from civic tech Jobs
-Sean from civic Tech Index
-Henlatourrette from 100 automations
-Josh from VRMS
-Eric from 311 data

**Comment by SheIsBukki** [comment]
@Evon081 Thanks for the consistent updates. Let us know if you have any blocker

**Comment by Evon081** [comment]
have reached out to the team leads of the following projects as regards my issue:
https://github.com/hackforla/product-management/issues/50

VRMS - Josh Bubar
Open community survey - Kaylani
lucky parking - Greg Pawin
home unite us - Regan Hutson
ESM triage - skip projects that are closed
TDM calculator - kevin Howley
hack website - Providence
Engage - Bryon Hart
Expunge Assist - Tom Demoner
Civic Tech Structure - skip / no active channel
Design Systems - Yasaman
Civic Tech Index - Sean Sada
Civic Tech Jobs - Danish or Sharhad
Brigade Playbook - signup for code for america (slack slack.codeforamerica.org) [#organizers-playbook](https://cfa.slack.com/archives/C019RCM15FE)
Civic Opportunity Project - skip
Access the Data - Lucy or Aj Price
100 automations - Henry Latourrette
311 data - Eric Cho

responses -

I have had zoom meetings with the following PMs:
- Access The Data, Lucy Chang.
- Design Systems, Yasaman 
- 100 Automations, Henry
- Civic Tech Jobs, Danish
- 311 Data, Eric Cho
- VRMS, Josh Bubar

I am currently setting up meetings with the following PMs-
- Expunge Assist, Thomas Demoner
- Lucky Parking, Greg Pawin
- Civic Tech Index, Sean Sada
- Home Unite Us, Regan Huston
- Hack Website, Providence

I couldnt find "Kaylani" in the open community survey channel.

**Comment by SheIsBukki** [comment]
@Evon081 Thanks for the update, we will talk about your blocker at the next meeting

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Kalyani is `@Kalyani Raman` in the [#community-survey](https://hackforla.slack.com/archives/C01H0HUDMCK) channel

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
send 2 week message on 2022-05-13

**Comment by Evon081** [comment]
I have had zoom meetings with the following PMs:

Access The Data, Lucy Chang.
Design Systems, Yasaman
100 Automations, Henry
Civic Tech Jobs, Danish
311 Data, Eric Cho
VRMS, Josh Bubar

I am currently setting up meetings with the following PMs-

Expunge Assist, Thomas Demoner
Lucky Parking, Greg Pawin
Civic Tech Index, Sean Sada
Home Unite Us, Regan Huston
Hack Website, Providence
Blocker:
I couldnt find "Kaylani" in the open community survey channel.

**Comment by ExperimentsInHonesty** [comment]
@Evon081 I don't know what you mean, by 

> I couldnt find "Kaylani" in the open community survey channel.

Are you saying she has not posted recently, or you tried to write to her and cannot?

She is on the project and will respond if you message her in the channel

@Kalyani Raman in the [#community-survey](https://hackforla.slack.com/archives/C01H0HUDMCK) channel

**Comment by ExperimentsInHonesty** [comment]
- Please update https://github.com/hackforla/product-management/issues/50 with all your findings from each team.  This is prior to writing a guide.  So at this point, you would just be adding all your notes.  See this issue for an example: https://github.com/hackforla/UI-UX/issues/62#issuecomment-1119710480

**Comment by ExperimentsInHonesty** [comment]
Please explain when you say that Regan has not responded to you.  It looks like he has.
![image](https://user-images.githubusercontent.com/37763229/169552874-a43a7742-91cf-4a9f-87b6-451ee41aebb3.png)

I don't see any recent messages to Sean or anyone on the Civic Tech Index Channel.

I see one message to Kalyani today, so I doubt she would have responded to you yet since its 6am her time when you sent the message.  If you don't get a response by Monday at 12 pm PST (your 9pm) you could drop in on the team meeting by asking in the slack channel if you can join them for the meeting or ask to be added to the agenda. 

Providence has been out for the past month because she was working on her dissertation for her PhD.  She is back now.  Try again.  And if she does not respond, you can ask me.  I am the other PM on that project.  I am available during our Guides Meeting time.

**Comment by Evon081** [comment]
> @Evon081 Please explain when you say that Regan has not responded to you. It looks like he has. ![image](https://user-images.githubusercontent.com/37763229/169552874-a43a7742-91cf-4a9f-87b6-451ee41aebb3.png)
> 
> I don't see any recent messages to Sean or anyone on the Civic Tech Index Channel.
> 
> I see one message to Kalyani today, so I doubt she would have responded to you yet since its 6am her time when you sent the message. If you don't get a response by Monday at 12 pm PST (your 9pm) you could drop in on the team meeting by asking in the slack channel if you can join them for the meeting or ask to be added to the agenda.
> 
> Providence has been out for the past month because she was working on her dissertation for her PhD. She is back now. Try again. And if she does not respond, you can ask me. I am the other PM on that project. I am available during our Guides Meeting time.

**Comment by Evon081** [comment]
Apologies for not being specific.

Regan, insisted he doesnt have much to share but would love to hear about the best practices we learn from other teams.
The plan is to get back to him after talking to every team i can reach.

I was having conversations with Sean via DM. We had a meeting fixed for last week but he canceled. we are yet to fix a new 
meeting date.

I would hold on for feedback from Kalyani, if i don't get any i would request to join the Monday meeting.

I have also reached out to providence via the HFLA-SITE channel.
hoping for a swift response.

I still have a meeting with Gordon on Thursday 26th may 2022.

**Comment by ExperimentsInHonesty** [comment]
@Evon081 I added this comment to the PM agenda for this team https://github.com/hackforla/website/issues/2212#issuecomment-1141230473

**Comment by Evon081** [comment]
I had a meeting with Gordon Ruby on Thursday the 26th of may.
I have annotated my findings in #https://github.com/hackforla/product-management/issues/50

**Comment by Evon081** [comment]
> @Evon081 I added this comment to the PM agenda for Providence [hackforla/website#2212 (comment)](https://github.com/hackforla/website/issues/2212#issuecomment-1141230473)

Still waiting on a response from providence

**Comment by Evon081** [comment]
UPDATE
-The meeting with Kylani on Tuesday didn't hold due to a time misunderstanding. 
we are working to fix a suitable time for us.
-I will meet with Sean Sada between the 4th and the 6th when he said he will be available. however, we havn't fixed a time and a date.
-

**Comment by ExperimentsInHonesty** [comment]
@Evon081 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Evon081** [comment]
UPDATE:
- I still haven't had a meeting with kaylani. 
  After we couldn't have the last scheduled meeting, she has not responded to my last message on the slack channel. 
   i needed an email to schedule a meeting.
- Sean Sada hasn't responded about his availability after 6th of june.
- Providence is also irresponsive.

**Comment by Evon081** [comment]
-I have a meeting with Kalyani tomorrow 12:15am WAT.
-No response from sean sada 
-No response from Providence

**Comment by SheIsBukki** [comment]
@Evon081 Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
@Evon081  Please provide an update

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Evon081** [comment]
-SEAN SADA said he would be available from 20th of june, but didn't respond after that.
-I have reached out to jessica Cheng on the hfla cannel and we have a meeting on the 19th 8am pacific daylight time.

**Comment by Evon081** [comment]
-I had a meeting with Jessica Cheng on the 19th Pacific daylight time 
- I have reached out to Sean Sada once more on the civiv tech index channel

**Comment by Evon081** [comment]
I have successfully had meetings with the following teams and have annotated my findings.


VRMS - Josh Bubar
Open community survey - Kaylani and Ambareen
lucky parking - Greg Pawin
hack website - Jessica Cheng
Expunge Assist - Tom Demoner
Design Systems - Yasaman
Civic Tech Jobs - Danish 
Access the Data - Lucy 
100 automations - Henry Latourrette
311 data - Eric Cho

**Comment by Evon081** [comment]
> @Evon081 Sean is off the project now. There is no longer any pm on the civic tech index project

Thanks for the reply. Kevin Phan has reached out to me from the team

**Comment by SheIsBukki** [comment]
@Evon081 Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Evon081** [comment]
> @Evon081 Please provide an update
> 
> Progress: "What is the current status of your project? What have you completed and what is left to do?" Blockers: "Difficulties or errors encountered." Availability: "How much time will you have this week to work on this issue?" ETA: "When do you expect this issue to be completed?" Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

UPDATE:
 Id like to believe i have finished gathering examples, as i have had meetings with the various active teams i could find on slack, with exception of the civic tech index which bonny stated that there is no active PM.
However, after that information Kevin Phan reached out to me from the civ tech index slack channel but stopped responding to my messages when i replied.

**Comment by SheIsBukki** [comment]
> > @Evon081 Please provide an update
> > Progress: "What is the current status of your project? What have you completed and what is left to do?" Blockers: "Difficulties or errors encountered." Availability: "How much time will you have this week to work on this issue?" ETA: "When do you expect this issue to be completed?" Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
> 
> UPDATE: Id like to believe i have finished gathering examples, as i have had meetings with the various active teams i could find on slack, with exception of the civic tech index which bonny stated that there is no active PM. However, after that information Kevin Phan reached out to me from the civ tech index slack channel but stopped responding to my messages when i replied.

So, since you said Bonnie already told you that there's no active PM in the project, you can go ahead to conclude the Gather Example phase, and move to the next stage.

**Comment by SheIsBukki** [comment]
@Evon081 We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by Evon081** [comment]
> @Evon081 We did not hear from you last week after we reached out, please provide the following update in this issue.
> 
> 1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
> 2. Blockers: "Difficulties or errors encountered."
> 3. Availability: "How much time will you have this week to work on this issue?"
> 4. ETA: "When do you expect this issue to be completed?"
> 5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
> 
> If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

Apologies for the late response and update. 
I do not have any update as i do not know next steps after gathering examples. 
Spoke to Bonnie about it at the last PM CoP meeting i attended and she said wed talk about it when next she's in our meeting.

**Comment by Evon081** [comment]
UPDATE: 
i am still waiting for instructions on next steps. 

I have finished gathering examples for the issue https://github.com/hackforla/product-management/issues/50 
I have had meetings with the various active teams i could find on slack, with exception of the civic tech index which bonny stated that there is no active PM.

**Comment by ExperimentsInHonesty** [comment]
@Evon081 I left you a comment on https://github.com/hackforla/product-management/issues/50#issuecomment-1256401281

**Comment by Evon081** [comment]
UPDATE: i am currently working on the summary that Bonnie talked  on 
https://github.com/hackforla/product-management/issues/50#issuecomment-1256401281 about 5 days ago. 
will have it ready by friday.
