### ISSUE TITLE
Onboarding: Adeniyi Deborah

### ISSUE THREAD

**Issue by Toluwani-Deborah** [hackforla/guides#86]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  So any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.

### Action Items
- [x] Create a google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: 
- https://docs.google.com/document/d/1OWELQMGU8rWNn_Xbvmy7SHlBodK0gaag4kjLM5iH2zY/edit
- Guide you are working on
   - Name of guide: GP: How to Gather Examples and Interview Teams (CoP presentation)
   - URL of guide Issue: https://github.com/hackforla/product-management/issues/20

**Comment by ExperimentsInHonesty** [comment]
When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Toluwani-Deborah** [comment]
Name of guide: Create a guide: Figma effective practices
https://github.com/hackforla/product-management/issues/20

**Comment by ExperimentsInHonesty** [comment]
@Toluwani-Deborah  Please review the [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit) and use it to work on the guide.  Slide # 4 has an instruction for you to assign yourself to the guide issue that you choose, which it looks like you have not done.

**Comment by ExperimentsInHonesty** [comment]
@Toluwani-Deborah The file you created for your notes is in your personal google drive.  Please move it to - Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)

**Comment by ExperimentsInHonesty** [comment]
@Toluwani-Deborah Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Toluwani-Deborah You still need to move your document to the team folder.  Only you can see the document.  

We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
no response yet, check again 2022-03-16

**Comment by ExperimentsInHonesty** [comment]
@Toluwani-Deborah  The document is still in your personal drive.  I am copying you notes here, since we will probably at some point lose access to the document

> There should be a pictorial representation or a screenshot as to how the guide issue and the sub issue should be created.
> I noticed a progression of steps all through the slide but these slides project different information. I think each section should be independent of other sections with each having its own independent explanation and know-how.

We have not heard from you via this issue or slack for 3 full weeks.  We are going to remove you from the team resources  You are welcome to come back, when you are ready, you can message us in the [#guide](https://hackforla.slack.com/archives/C028T9XU9S5) Slack channel to be re-added.
