### ISSUE TITLE
Onboarding: EDING

### ISSUE THREAD

**Issue by AedingM** [hackforla/guides#87]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  So any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.

### Action Items
- [x] Create a google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: 
- Guide you are working on
   - Name of guide
      - Create a Guide/Template: Landing page with mailing list (pre product launch) for your project #132
   - URL of guide Issue
      - https://github.com/hackforla/product-management/issues/132

**Comment by ExperimentsInHonesty** [comment]
When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Aeding Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
@AedingM reached out on Slack

Hi Bukki, how are you doing?
[02/25/2022](https://hackforla.slack.com/archives/D033CT0785Q/p1645800265480229)
I’m having major issues with my laptop and I know it’s key for the sessions. I will like to get about a week to sort it out. Is that fine?

**Comment by ExperimentsInHonesty** [comment]
@AedingM Do you have a computer?  Or only a mobile device?  If mobile, Is that a temporary condition or permanent?

**Comment by AedingM** [comment]
@ExperimentsInHonesty I do not have a laptop at the moment, mainly mobile device. However, it is a temporary condition, my laptop is taking longer than expected to sort out.

**Comment by ExperimentsInHonesty** [comment]
@AedingM Please provide a general ETA on when you think you will have a computer again?

**Comment by AedingM** [comment]
@ExperimentsInHonesty It's looking like I will need to wait till the end of the month for the computer to get sorted. I will have access to a computer on odd days though when I use someone else's.

**Comment by ExperimentsInHonesty** [comment]
Check back on them on 2022-04-01

**Comment by ExperimentsInHonesty** [comment]
@AedingM 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@AedingM 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

Next message 2022-04-15

**Comment by ExperimentsInHonesty** [comment]
@AedingM We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by AedingM** [comment]
@ExperimentsInHonesty I am currently experiencing difficulties due to the fact that I am yet to resolve my laptop issues. 
I am fine to take some time off and come back when it's resolved if that works.

**Comment by ExperimentsInHonesty** [comment]
@AedingM.  OK we will remove you from the team, for now,  and you can message us in the ```#guides``` slack channel when you are ready to come back.
