### ISSUE TITLE
Onboarding: Abasiayene Deborah Umoh 

### ISSUE THREAD

**Issue by abasiayene** [hackforla/guides#89]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
- [ ] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [ ] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [ ] Review the Presentation for Gathering Examples
- [ ] Pick a guide 
   - [ ] Note the Name of guide and URL of the guide in the comments below
- [ ] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on gather presentation - Deborah abasiayene umoh](https://docs.google.com/document/d/1-1U_dDRFKCZ6m_jVUZyc_-l2YtMV2HI8CGMse8PDZ6w/edit)
- Guide you are working on
   - Name of guide
   - URL of guide Issue

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@abasiayene Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@abasiayene You need to provide the name and the link for the guide you are working on (picking the guide happens while you are reviewing the slide deck, on slide 8).  Please put that link and name above where it says

- Guide you are working on
  - Name of guide
  - URL of guide Issue

**Comment by ExperimentsInHonesty** [comment]
@abasiayene
Please provide update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
We have not heard from you via this issue or slack for 3 full weeks.  We are going to remove you from the team resources  You are welcome to come back, when you are ready, you can message us in the [#guide](https://hackforla.slack.com/archives/C028T9XU9S5) Slack channel to be re-added.
