### ISSUE TITLE
Create a Master Spreadsheet for all Community of Practice Templates and Guides Tracking Sheet

### ISSUE THREAD

**Issue by gautham-l** [hackforla/guides#9]
### Overview
As a Guides Team Admin, I want a spreadsheet with all the community of practice team's templates and guides tracking sheets under one sheet so that the guides team member can update the tracker.

### Action Items
- [x] Access all Community of Practice (COP) tracker sheets and copy them into a new sheet.
- [ ] Need to confirm where to store the new sheet.

### Resources/Instructions
- [All CoP Teams Tracker Sheet](https://docs.google.com/spreadsheets/d/10aQ54YMEFao__102XMRl7hhK5Yfp_YQuV2UD353dOmo/edit?usp=sharing)

**Comment by gautham-l** [comment]
Created and updated master spread [sheet ](https://docs.google.com/spreadsheets/d/10aQ54YMEFao__102XMRl7hhK5Yfp_YQuV2UD353dOmo/edit#gid=0) and stored under [Google Shared Drive location](https://drive.google.com/drive/folders/1MfC9chrrPozQZsq02wBzXjDsQKpoPz7_?usp=sharing).

- Copied PM teams tracker sheet format and content.
- Updated UI/UX, Revenue and Engineering team's tracker by filtering issues as there was no tracker with content.
- Marketing, Data Science, Ops and Admin teams are yet to create guides.

**Comment by gautham-l** [comment]
I created this issue since CoP Leads are not able to manage their individual team's roster. The reason guides team created a master sheet containing rosters of all teams is so they can keep the roster update manually and automate this process in the future.

**Comment by edwardsarah** [comment]
Believe this is managed with the [new guide tracker](https://docs.google.com/spreadsheets/d/1doIUMhwV3k2nUCdVyAEOQ7FiQbCWJAV4TTfuHp9u0Cs/edit?usp=sharing) and the guides tracker project board
