### ISSUE TITLE
Onboarding: Eloka Ogbonnia

### ISSUE THREAD

**Issue by Eloks7** [hackforla/guides#90]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [x] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather presentation - Ogbonnia Eloka](https://docs.google.com/document/d/1TgvK5pLO1LGkqhnd9uNPHCyN4Tq6CaBMLJZ7w5Tqugo/edit?usp=drivesdk) 
- Guide you are working on
   - Name of guide: [Figma Auto-Layout](https://github.com/hackforla/UI-UX/issues/62)
   - URL of guide Issue: [https://github.com/hackforla/UI-UX/issues/62](https://github.com/hackforla/UI-UX/issues/62)

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Eloks7** [comment]
1. I have been able to complete four tasks on my onboarding issue.
2. Don't really understand what is meant by guides.
3. I will have about 2-3 hours to work on this.
4. Should be completed in a week or two.

**Comment by Eloks7** [comment]
1. I have picked a guide and I am currently working on it.
2. Some difficulty understanding the presentation which I am using to work on the slide.
3. Will spend around 3 hours working on the issue this week.
4. 2 weeks hopefully.

**Comment by Eloks7** [comment]
1. Completed Method 1 of Step 4.
2. Don't really understand step 3.
3. 2 hours.
4. 3 weeks

**Comment by Eloks7** [comment]
1. Completed Methods 1, 2 and 3 of Step 4 finding only one example so far. Moved to Step 5.
2. Methods 4 and 5 of Step 4 are really confusing.
3. 3 Hours
4. 3 Weeks

**Comment by ExperimentsInHonesty** [comment]
Please annotate your guide issue with details about what you checked.

**Comment by Eloks7** [comment]
1. No update.
2. Will work on it this weekend.
3. 3 hours

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 thanks for the update

**Comment by Eloks7** [comment]
1. Currently contacting teams and confirming who their design leads are.
2. A long list of projects to go through.
3. 2 hours
4. 1 Month

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 
Your issue for the guides needs to be updated too with what you are doing.  So if you are reaching out to the teams via slack or checking their wikis to try to figure out who is on their teams, you need to put who you have contacted and how into that issue.

**Comment by Eloks7** [comment]
1. Contacting design team leads and setting up meetings.
2. Slow responses and still a lot of projects to be handled.
3. 2 hours
4. 1 Month

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/UI-UX/issues/62#issuecomment-1069226578

**Comment by Eloks7** [comment]
1. Still using the guide to set up meetings with leads.
2. Having serious electricity problems.
3. 2 hours
4. 2 months

**Comment by Eloks7** [comment]
1. Sent messages to all the projects requesting for their team's design leads for the guide I am working on.
2. Slow responses and time constraints.
3. 2 hours.
4. Don't know.

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 You are making good progress.  At the next guides meeting you attend, let's talk about:
How the guidance for reaching out to teams can be improved based on what you are learning about what works and what does not.  If you have thoughts about that now, don't forget to annotate your [GT: Notes on Gather presentation - Ogbonnia Eloka](https://docs.google.com/document/d/1TgvK5pLO1LGkqhnd9uNPHCyN4Tq6CaBMLJZ7w5Tqugo/edit?usp=drivesdk) document with observations and suggestions for improvement.

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 please recheck slide #20 to see if you comment can be resolved

**Comment by ExperimentsInHonesty** [comment]
Message in slack today
[Exon](https://app.slack.com/team/U0369H811S7):speech_balloon:  [4:52 AM](https://hackforla.slack.com/archives/C028T9XU9S5/p1649850774938349)
Hi Team. I've been having electricity issues since last week and I haven't updated because of this. I also cannot make it to the meeting today. I apologize about this. Thanks

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 please recheck [this slide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g10c22cb8a35_0_88) to see if your comment can be resolved.  We understand if you can't make the meeting, but please try to move your issue forward if you are able to get online.

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 It looks like you are making progress communicating with people.  But you are not annotating the details of your conversations in your issue. I have provided an [example](https://github.com/hackforla/UI-UX/issues/62#issuecomment-1101499835), so that you can see what we expect.  Please add all your conversations into the issue before they disappear on slack.  We are off the free trial, so we only go back about 28 days (the length of time gets smaller when people put large images into slack).  _If you don't screenshot your conversations by the next time I look at this issue, I will do it for you, but I won't be happy about it._

Also, if someone references me in the conversation, and I don't respond, please highlight that here, in this issue, so that I can help you move it forward.  You can see by my autoresponder that I don't read Slack messages because of the sheer volume of them that comes in.

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 follow up note to above https://github.com/hackforla/guides/issues/90#issuecomment-1101502489
Its already too late to wait for you to do screen shots of your conversations.  I am going to make them right now, but I won't summarize them, you need to do that.  And for now on, you MUST update your issue as you go because otherwise you are wasting your time and theirs because you or someone else will have to have these conversations all over again, as they will be missing from slack when you go record them.

**Comment by SheIsBukki** [comment]
@Eloks7 Please provide us with an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 will reach out to the people who responded (which can be found on his issue https://github.com/hackforla/UI-UX/issues/62) and finish the conversation.

**Comment by Eloks7** [comment]
1. Created a sub issue for teams that are yet to give me a feedback on the Auto-Layout issue.
2. Slow responses.
3. 2 hours.
4. No idea

**Comment by ExperimentsInHonesty** [comment]
I created a comment at the bottom of your issue where I summarized all the communication from prior comments.  See this [new slide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g1282bd70f28_0_26) where we are explaining how to capture the status of outreach

**Comment by ExperimentsInHonesty** [comment]
@Eloks7  I created a comment at the bottom of your issue where I summarized all the communication from prior comments.  See this [new slide](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g1282bd70f28_0_26) where we are explaining how to capture the status of outreach.  Please update that comment with next steps for all the projects.

### Civic Tech Jobs
- Question: This completes the gathering of example. Do we need to do anything else?  For instance, interviewing her about how it is working for them on the project, and what the challenges its presents are, or if they have any rules

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 Its been 12 days since we last communicated.  Please provide an update.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If no response by 2022-05-20 send two week message

**Comment by ExperimentsInHonesty** [comment]
@Eloks7 We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.
