### ISSUE TITLE
Onboarding: Funke Olatunbosun

### ISSUE THREAD

**Issue by Funmikee** [hackforla/guides#93]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [ ] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather Presentation - Funke Olatunbosun](https://docs.google.com/document/d/1PpTZCzNXQDFwl9kP_OtXOxRwjc4oEyGVenq_puDfvrY/edit?usp=sharing)
- Guide you are working on
   - Name of Guide: Partner Outreach Email Template 
   - URL of guide Issue: https://github.com/hackforla/product-management/issues/224 

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Funmikee I look forward to hearing about your progress at the next meeting you attend.

**Comment by Funmikee** [comment]
> @Funmikee I look forward to hearing about your progress at the next meeting you attend.

Definitely :)
A quick question, the gathered examples can be for any type of partner outreach, correct?

**Comment by ExperimentsInHonesty** [comment]
> Q: A quick question, the gathered examples can be for any type of partner outreach, correct?
A: Yes, every type of partner outreach is appropriate for the guide

**Comment by ExperimentsInHonesty** [comment]
Funke has been adding the checkboxes per team for all the resources she has checked.  She is up to 9 team teams, finding 4 assets so far.

**Comment by Funmikee** [comment]
I won't be able to work on this until next week because my trip was rescheduled and I need to rush things. I should be settled in by Sunday and will return to the task by Monday (21st March)

**Comment by Funmikee** [comment]
> @Funmikee thanks for the update. Hope your trip was good

Thanks, Bonnie, my trip was great just down with fever due to a change of environment.

**Comment by Funmikee** [comment]
Progress: I added 9 more projects that I checked, and I found 5 assets in total from 2 projects.
Blockers: I need access to https://github.com/hackforla/expunge-assist document 
Availability: 3 hours 
ETA: I will check the remaining projects before the week runs out.

**Comment by ExperimentsInHonesty** [comment]
Thank you for the update, I fixed the permissions issue.  Looking forward to next.

**Comment by Funmikee** [comment]
I was unable to work on the issue yet; I will find assets for the remaining four projects, and then I will contact all of the projects without any assets via Slack.

**Comment by SheIsBukki** [comment]
@Funmikee thanks for the update, let us know if you have any blocker...

**Comment by Funmikee** [comment]
Progress: I've finished searching for all projects, I'll start sending Slack messages to the project team members where I couldn't find any assets.
Blockers: How do I contact a few projects that have no assets and do not have a Slack channel?
Availability: 3-5 hours

**Comment by ExperimentsInHonesty** [comment]
@Funmikee All the projects except Civic Tech Structure do have channels.  Check Hackforla.org for the ones you are missing.

**Comment by ExperimentsInHonesty** [comment]
@Funmikee It looks like you are making good progress looking through the project's slack channels.  During the next meeting you attend, let's review the issues you have raised in this document [GT: Notes on Gather Presentation - Funke Olatunbosun](https://docs.google.com/document/d/1PpTZCzNXQDFwl9kP_OtXOxRwjc4oEyGVenq_puDfvrY/edit?usp=sharing) to see if we can resolve them.

**Comment by ExperimentsInHonesty** [comment]
Sent 2 week message on 2022-04-15

**Comment by ExperimentsInHonesty** [comment]
@Funmikee 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Funmikee We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
Check this issue on 2022-04-22. If no response, send 3 week message

**Comment by SheIsBukki** [comment]
@Funmikee We have not heard from you via this issue or slack for 3 full weeks. We are going to remove you from the team resources  You are welcome to come back, when you are ready, you can message us in the [#guide](https://hackforla.slack.com/archives/C028T9XU9S5) Slack channel to be re-added.
