### ISSUE TITLE
Onboarding: Feyi Akinyode

### ISSUE THREAD

**Issue by FeyiA** [hackforla/guides#94]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - Feyi Akinyode``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [x] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [x] Leaving comments in the presentation if you have a suggested improvement
   - [x] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather Presentation - Feyi Akinyode](https://docs.google.com/document/d/1D215ZuoW-HV2IKJNf6Y2tFjyhpto9Mb0Y5cpTlPLeU8/edit?usp=sharing)
- Guide you are working on
   - Name of Guide: Product Analytics Best Practices 
   - URL of guide Issue: https://github.com/hackforla/product-management/issues/73

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by FeyiA** [comment]
Create a Guide: Product Analytics Best Practices #73

https://github.com/hackforla/product-management/issues/73

Progress: I have looked at two out of twenty five projects.
Blockers: Not sure about the exact terms I should be searching for while looking at the projects. 
Availability:  I will be able to work on this issue for 9 hours this week 
ETA: "When do you expect this issue to be completed?" I should be able to close this out by March 31 
Pictures (if necessary):

**Comment by ExperimentsInHonesty** [comment]
Gave Feyi a overview of how to check a project

**Comment by FeyiA** [comment]
Bonnie's overview provided clarification. 

Work on assigned issue is in progress.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA thanks for the update.  I Just reviewed the progress in the guide issue.  Looks good!

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Thanks for the notes, we updated the presentation based on them.

**Comment by FeyiA** [comment]
Corrected the formatting on https://github.com/hackforla/product-management/issues/73 like Bonnie advised.

Work is still in progress.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA thanks for the update and for making the changes.  I look forward to next.

**Comment by SheIsBukki** [comment]
@FeyiA Please provide an update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by FeyiA** [comment]
1. Progress: Still on checking for examples, I have checked all slack channels for examples, I am yet to check the Wiki, issues and Project cards. 
2. Blockers: Non for now.
3. Availability: 6 hours this week 
4. ETA: Not certain as of now

**Comment by ExperimentsInHonesty** [comment]
@FeyiA left you a note on the guide issue https://github.com/hackforla/product-management/issues/73#issuecomment-1085964395

**Comment by FeyiA** [comment]
> @FeyiA left you a note on the guide issue [hackforla/product-management#73 (comment)](https://github.com/hackforla/product-management/issues/73#issuecomment-1085964395)

Saw it, thanks, issue raised has been resolved.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by FeyiA** [comment]
Progress: Still on checking for examples, I have checked all slack channels for examples, I am yet to check the Wiki, issues and Project cards.
Blockers: None for now.
Availability: wasn't available to do do much work this week. Should be able to spend at least 6 hours on working next week. 
ETA: Not certain as of now

**Comment by ExperimentsInHonesty** [comment]
@FeyiA You closed this issue, I don't think you meant to do that.

**Comment by FeyiA** [comment]
> @FeyiA You closed this issue, I don't think you meant to do that.


No I did't mean to. 

Thank you.

**Comment by FeyiA** [comment]
Progress: Still checking for examples, should be done checking by Friday 15th April 
Blockers: None for now.
Availability: 10 hours this week
ETA: Not certain as of now

**Comment by FeyiA** [comment]
Progress: I'm about 75% done with checking for examples
Blockers: None yet
Availability: 4 hours 
ETA: I'm working towards completing checking for examples by Monday 25th April, not sure about other tasks. 
Pictures (if necessary): Pictures are being added.

**Comment by SheIsBukki** [comment]
@FeyiA Thanks for the update. We appreciate regular updates just as much as we appreciate working on issues. 

We will check back on the 25th of April to see your progress on checking for examples.

**Comment by FeyiA** [comment]
I fell ill and couldn't work do any work as expected. I will get to it as soon as I'm well.

**Comment by SheIsBukki** [comment]
@FeyiA Sorry about that, please take care of yourself 😊

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Please let us know if you are feeling well enough to come back.

**Comment by FeyiA** [comment]
I am better now and have resumed working on the issue.

Thank you.

**Comment by ExperimentsInHonesty** [comment]
Great.  We look forward to getting a progress update when we check your issue on Monday or Wednesday.   Please use this format:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
Hi @FeyiA, good to have you back. Can you share an update on what you've done about your guide in the last few days? 

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@FeyiA reminder that we require an update weekly.

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by FeyiA** [comment]
Progress: One last example to check then I'll proceed to drafting a template 
Blockers:
Availability: 4 more hours this week
ETA: Can't say 
Pictures (if necessary): Added

**Comment by ExperimentsInHonesty** [comment]
@FeyiA I am out from the 21st to the 27th of each month.  Please list out the files that you do not have access to, in your issue.  I could have added access today, before I take my time off, but I don't see the list in the issue.

**Comment by FeyiA** [comment]
@ExperimentsInHonesty 

Please see the list below


Links that require access

311 Data

[Hot Jar Notes of V1]
https://docs.google.com/spreadsheets/d/1-71hlngdeysgF0Sd5LtfnaWzuAFx_2ZJvBC_07LC3VY/edit?usp=sharing

[Data Analysis google docs]
https://drive.google.com/drive/u/1/folders/1xMr8MjDO17LYQBLI1pXsozhro46ZxVzy

[Existing BI Dashboard with 311 Data]
https://empowerla.org/demographics-BI/



TDM Calculator 
[Develop Template to apply analytics to other web products]
https://docs.google.com/document/d/14t06vRGA9DhpxEjZqWascmBqhsVJFohcMUDb0DaLSIk/

**Comment by ExperimentsInHonesty** [comment]
@FeyiA 
### I am able to load this without special permissions
[Existing BI Dashboard with 311 Data]
https://empowerla.org/demographics-BI/


### I gave you access to 
[Hot Jar Notes of V1]
https://docs.google.com/spreadsheets/d/1-71hlngdeysgF0Sd5LtfnaWzuAFx_2ZJvBC_07LC3VY/edit?usp=sharing

TDM Calculator
[Develop Template to apply analytics to other web products]
https://docs.google.com/document/d/14t06vRGA9DhpxEjZqWascmBqhsVJFohcMUDb0DaLSIk/

### I don't have access to this file and have requested they move it into the 311 project drive
[Data Analysis google docs]
https://drive.google.com/drive/u/1/folders/1xMr8MjDO17LYQBLI1pXsozhro46ZxVzy

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Can you provide the link to the page where you are seeing the link to this 
[product management google drive](https://drive.google.com/drive/folders/1lO8k_0Z1UejkuRlNMYlUl2xlqgyBmvrF?usp=sharing)

Its a link to a drive we don't use anymore and I want to update it with the new location.

**Comment by FeyiA** [comment]
@ExperimentsInHonesty it's instructions for creating a guide page

https://github.com/hackforla/product-management/issues/73

![image](https://user-images.githubusercontent.com/101159525/172181699-e8916ece-9324-474f-aac2-1a4df07c8f68.PNG)

**Comment by ExperimentsInHonesty** [comment]
@FeyiA I updated your guide issue with a new link.  The old link is to the old drive.  This is what it looks like now 
![image](https://user-images.githubusercontent.com/37763229/174337937-716c2e36-9a49-42fe-ba6f-0ccf13901271.png)

Thanks for letting us know that was going to the old resource.  We have updated the template in the PM repo too.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA 

We have not heard from you since June 6th please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you by 2022-07-15, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
@FeyiA Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by FeyiA** [comment]
Progress: I have created a document in the shared drive and I'm working on fleshing out the document.
Blockers: None
Availability: 6hrs
ETA: Soon
Pictures (if necessary):

**Comment by SheIsBukki** [comment]
@FeyiA Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
@FeyiA We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by SheIsBukki** [comment]
We have not heard from you via this issue or slack for 3 full weeks.  We are going to remove you from the team resources  You are welcome to come back, when you are ready, you can message us in the [#guide](https://hackforla.slack.com/archives/C028T9XU9S5) Slack channel to be re-added.
