### ISSUE TITLE
Onboarding: Mercy

### ISSUE THREAD

**Issue by pm-merciee** [hackforla/guides#95]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [ ] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [ ] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather presentation - Mercy Madunagu](https://docs.google.com/document/d/1gCziYQdi3n6CNqviX8EBX3bC8KMqNVGQz-uHaiwMQRA/edit)
- Guide you are working on
   - Name of guide: [Create a Guide/Template: to making a training deck for your project #265]
   - URL of guide Issue: [https://github.com/hackforla/product-management/issues/265]

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@pm-merciee Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by pm-merciee** [comment]
1. Progress: I have been able to complete 5 out of my 12 issues. I have 7 left
2. Blockers: None for now.
3. Availability: I intended to dedicate at least 4hrs this week.
4. ETA: I hope to complete it before next Wednesday's meeting.
5. Pictures: None

**Comment by ExperimentsInHonesty** [comment]
@pm-merciee I reviewed your observations doc and changed the formatting a little to indicate the problem/recommendation/response/resolved status.  Please note in this issue, once you pick a guide.  

FYI, your estimate of when you will complete this task is a bit ambitious, meaning, there is no way you are completing the entire thing in 4 hours or even in two weeks (by next week's team meeting).    I look forward to your next estimate after you have assigned yourself a guide and have gotten to slide 13, where you will have  a better idea of what is involved.

**Comment by pm-merciee** [comment]
Hi @ExperimentsInHonesty I just finished my move, I should have feedback by the 28th.

**Comment by SheIsBukki** [comment]
Okay, will check back on the 30th of April

**Comment by ExperimentsInHonesty** [comment]
@pm-merciee Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@pm-merciee We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
Check this issue on 2022-04-22. If no response, send 3 week message

**Comment by pm-merciee** [comment]
1. Progress: I picked a guide, and I have been able to complete 6 out of my 12 issues. I have 6 left
2. Blockers: None for now
3. Availability: I intend to dedicate 6hours of work by this weekend
4. ETA: I will have better feedback on when I expect to finish this issue by 2022-04-25.
5. Pictures (if necessary): no pictures available for now

**Comment by SheIsBukki** [comment]
@pm-merciee Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@pm-merciee We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by SheIsBukki** [comment]
@pm-merciee We did not hear from you last week after we reached out, please provide the following update in this issue. 
 
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
Remove @pm-merciee on Monday  2022-05-13 if no response
