### ISSUE TITLE
Onboarding: Sarah Mbagwu

### ISSUE THREAD

**Issue by Sarah-Nonye** [hackforla/guides#96]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [x] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [ ] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather presentation - Sarah Nonye](https://docs.google.com/document/d/1BXCEhrgsvgkiHf-YRY11_FJ11wSADa1oJse2WEZ9-Hg/edit)
- Guide you are working on
   - Name of guide: Create a Guide/Template: User research for your project
   - URL of guide Issue: https://github.com/hackforla/product-management/issues/167

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Sarah-Nonye Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Sarah-Nonye** [comment]
1. Progress: I have completed 7 out of 12 tasks, I am not quite clear on the others and will need some assistance.
2. "Review the Presentation for Gathering Examples, Pick a guide", "Clean up your presentation notes
 Present to the Guides Team"
I have difficulties with these tasks and I am not able to complete them.
3. About 4hours this week
4. I hope to complete this issue before the next meeting.

**Comment by ExperimentsInHonesty** [comment]
@Sarah-Nonye You can come to any of our meetings (M-W-F) if  you need help clearing a blocker, or understanding anything.  

Re 4.: Not sure how you intend to complete the tasks if you don't understand what to do.

We look forward to seeing you at the next meeting

**Comment by SheIsBukki** [comment]
@Sarah-Nonye  Please provide an update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Sarah-Nonye We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
@Sarah-Nonye at our next meeting have us help you annotate this issue with the guide you are working on (with the link you already provided, but in the place we want you to record that).

**Comment by ExperimentsInHonesty** [comment]
- Next steps are to continue using  [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit) to work on your guide issue https://github.com/hackforla/product-management/issues/167, making notes in your Google Doc  [GT: Notes on Gather presentation - Sarah Nonye](https://docs.google.com/document/d/1BXCEhrgsvgkiHf-YRY11_FJ11wSADa1oJse2WEZ9-Hg/edit) with areas for improvement or concern that we can address at the next team meeting.

**Comment by ExperimentsInHonesty** [comment]
@Sarah-Nonye 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Sarah-Nonye 

We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
3 week message to be sent on 2022-04-25

**Comment by SheIsBukki** [comment]
@Sarah-Nonye

We have heard from you since we've been reaching out, please provide the following update in this issue.

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."
If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.
