### ISSUE TITLE
Onboarding: Isaiah Ozadhe

### ISSUE THREAD

**Issue by Tekkieware** [hackforla/guides#97]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [x] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [ ] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather presentation - Isaiah Ozadhe](https://docs.google.com/document/d/1k-DC3abTKlY-pKDTvIX85wH5nQc-KVjyjer3CWJPSeQ/edit)
- Guide you are working on
   - Setting up Git
   - URL of guide Issue:  [Create a Guide/Template: Setting up Git #16](https://github.com/hackforla/engineering/issues/16).

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Tekkieware** [comment]
@ExperimentsInHonesty 
Progress: Done with steps 1 to 5
Blockers: None
Availability: Not exactly sure.
ETA: I can't tell for now because the next part(picking and working on a guide) is still a bit hazy to me.
Pictures (if necessary): None.

**Comment by SheIsBukki** [comment]
We looked at @Tekkieware's observations and resolved some of them

**Comment by ExperimentsInHonesty** [comment]
@Tekkieware Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Tekkieware** [comment]
@ExperimentsInHonesty
Progress: Still on gathering examples for my guide. Searched about 12 projects so far(their wiki, slack, issues, project board and sometimes readme and contributing.md files). 12 more projects left unchecked.
Blockers: Not finding much information related to git or version control except for projects that have a contributing.md files.
Availability: Not exactly sure.
ETA: Should be able to finish gathering examples before the week runs out.
Pictures (if necessary): None.

**Comment by ExperimentsInHonesty** [comment]
@Tekkieware 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@Tekkieware 

We did not hear from you last week after we reached out, please provide the following update in this issue.  
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

If we do not hear from you in the next week, you will be removed from the project, until you are ready to come back.

**Comment by ExperimentsInHonesty** [comment]
If no response, send 3 week message on 2022-04-25

**Comment by Tekkieware** [comment]
@ExperimentsInHonesty I'm really sorry for not updating earlier. Something came up and I'll be away one more week.

**Comment by ExperimentsInHonesty** [comment]
@Tekkieware Please provide update.  It's been 27 days since your last progress report.  Do you want to be removed from the team?  If not, please make time for your tasks.  As I communicated during onboarding.  Hack for LA requires 6 hours a week to be on a project team.
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
remove on 5/11

**Comment by Tekkieware** [comment]
@ExperimentsInHonesty 
I think i have to step aside for a while. I have a lot going on and i'm struggling to keep up. I'll be back soon. My sincere apologies.

**Comment by ExperimentsInHonesty** [comment]
@Tekkieware Thanks for letting us know.  Reach out in the Slack channel anytime you are ready to come back.
