### ISSUE TITLE
Onboarding: Exon Nkemchor

### ISSUE THREAD

**Issue by Exonkenz** [hackforla/guides#99]
### Overview
We need an unbiased review of the gather presentation so that we can improve it.

#### Additional Details
You will be working on guide during this issue, but the purpose of this issue is to evaluate and improve the Gather Examples and Interview Teams presentation.  
- Any notes you have about the guide you will be making should be noted in the issue related to the Guide you choose.
- Any notes about the Gather Examples and Interview Teams presentation should be in the document you create.

### Action Items
- [x] Create a Google doc, with the name ```GT: Notes on Gather presentation - YOUR NAME HERE``` in the Gather Examples folder (customize with your name)
   - [x] Add the link to the document and its name in the Resources section below
- [x] Add to the notes document as you go, with observations about the Gather Presentation.  You will encounter some issues, such as font size or other types of formatting changes, what we are looking for though is material changes to the instructions.  For instance, if something could use a screenshot to make it clearer, and it doesn't have one or when you try to follow the steps, something is missing.
   - [x] If while looking at the presentation (not the guide), you encounter any words that you think should be added to our glossary,  please add them to the Glossary issue as comments.
- [x] Review the Presentation for Gathering Examples
- [x] Pick a guide 
   - [x] Note the Name of guide and URL of the guide in the comments below
- [x] Use the presentation to work on the guide
   - [ ] Leaving comments in the presentation if you have a suggested improvement
   - [ ] Putting any notes about the guide either in the guide or in the issue for the guide (as appropriate)
- [ ] Clean up your presentation notes
- [ ] Present to the Guides Team

### Resources/Instructions
- #88 
- [Guides Tracker](https://github.com/orgs/hackforla/projects/3)
- [Gather Examples and Interview Teams presentation](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit)
- [PM Templates and Guides Project board](https://github.com/hackforla/product-management/projects/2)
- Folder for Team notes and Guide Presentation: [Gather Examples](https://drive.google.com/drive/u/0/folders/15ybydhWpIYr9a3MyE2FZf1g-SJs-23Jl)
- Your presentation notes document file: [GT: Notes on Gather Presentation - EXON NKEMCHOR](https://docs.google.com/document/d/1iIyLounfqhQyFCaumvPnvNjBaXRycLh_aj7QjJZVCfI/edit)
- Guide you are working on
   - Name of guide: Designers Toolkit
   - URL of guide Issue: https://github.com/hackforla/UI-UX/issues/25

### When you do your update please provide
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Exonkenz** [comment]
Progress: Issue is on-going, making good progress. I have completed 5/12 on my issue. 7 is left to do on my issue.
Blockers: None for now.
Availability: I am done for now. Will continue into the new week.
ETA: I am done for now. Can't say specifically but will dedicate est 3-6hrs hours to working on it in the new week.
Pictures: None for now.

**Comment by ExperimentsInHonesty** [comment]
@Exonkenz thanks for the update

**Comment by SheIsBukki** [comment]
@Exonkenz 
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Exonkenz** [comment]
Name of guide: Designers Toolkit
URL of the guide: https://github.com/hackforla/UI-UX/issues/25#issue-813797821

**Comment by ExperimentsInHonesty** [comment]
@Exonkenz The first item action items on this issue is to make a document to put your notes.

> - [ ] Create a Google doc, with the name GT: Notes on Gather presentation - YOUR NAME HERE in the Gather Examples folder (customize with your name)
>   - [ ]  Add the link to the document and its name in the Resources section below

You have checked off the box, but we don't see your document.  Please come to the meeting so we can help you with this.

**Comment by Exonkenz** [comment]
I have left a clearer and more actionable step in my recommendations tab on my gather example folder.

**Comment by Exonkenz** [comment]
The start of exercises slide is great because it prompts the new user of something that needs to be done. I think it is very clear and fixes the issue.

**Comment by ExperimentsInHonesty** [comment]
@Exonkenz Please try to make some progress on this issue.  The commitment is 6 hours a week.  If you have made progress, other than the above comments, it's not clear because there is no update in this issue or in the guide issue you are assigned to.

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
@Exonkenz Please try to make some progress on this issue. The commitment is 6 hours a week. If you have made progress, other than the above comments, it's not clear because you didn't share any update in this issue or the guide issue you are self-assigned yourself.

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Exonkenz** [comment]
Progress: Issue is on-going. I have started gathering examples of design resources used by UX/UI designers at Hack for LA
Blockers: I have some difficulty on where I should annotate my findings. 
Availability: I am done for now, will continue was my confusion is cleared.
ETA: Can't say for now, as I make progress on the issue it would become clearer.
Pictures: None for now

**Comment by ExperimentsInHonesty** [comment]
@Exonkenz Please read Bukki's comment above and provide an update here and annotate your issue https://github.com/hackforla/UI-UX/issues/25 with what you are finding, even if the project you have reviewed has no resources.  That way we know when all the projects have been checked

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Exonkenz** [comment]
Progress: Issue is on-going. I am still gathering examples of design resources used by UX/UI designers at Hack for LA
Blockers: I am still struggling to find relevant examples on my guides issue. I need some more help on this.
Availability: I am done for now, will continue during the week.
ETA: Can't say for now, as I make progress on the issue it would become clearer.
Pictures: None for now.

**Comment by ExperimentsInHonesty** [comment]
Exon will continue gathering issues and tools from each of the projects.

**Comment by Exonkenz** [comment]
Progress: In concluding stages of gathering examples on my guides issue.
Blockers: None for now
Availability: Will continue working on it this week
ETA: Can't say for now, as I make progress on the issue it would become clearer.
Pictures: None for now

**Comment by ExperimentsInHonesty** [comment]
@Exonkenz Thanks for the update.  We will check in on your progress... noting here that you left off on Civic Tech Jobs

**Comment by Exonkenz** [comment]
Progress: Trying to create a Draft Toolkit document on no. 4 of my guides issue.
Blockers: I need help clarifying how to go about it.
Availability: Will continue working on it this week.
ETA: Can't say for now, as I make progress on the issue it would become clearer.
Pictures: None for now

**Comment by ExperimentsInHonesty** [comment]
Glad we were able to talk at the last meeting.  Looking forward to your next update 

1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Exonkenz** [comment]
I've filled out the Excel spreadsheet with relevant design resource information as said in our last meeting.

**Comment by SheIsBukki** [comment]
@Exonkenz thanks for sharing your update.

**Comment by Exonkenz** [comment]
The spreadsheet contains the design resource information that other designers can find useful however, they are not necessarily relevant to the issue.

**Comment by ExperimentsInHonesty** [comment]
Exon is going to pause working on the guide and work on slides in the gather presentation.  He will write the summary of what they learned (as short as possible) and the section content slide.

- [41](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g133aaa1b952_0_112)
- [43](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g133aaa1b952_0_120)
- [68](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g133aaa1b952_0_130)

**Comment by ExperimentsInHonesty** [comment]
Provided feedback and @Exonkenz is going to continue working on slides above

**Comment by Exonkenz** [comment]
I am done working on the [slides](https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g133aaa1b952_0_112)(https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g133aaa1b952_0_120) (https://docs.google.com/presentation/d/1gkPpgnOPv7lBckoLic3HAA7z_IkeTnCw9ImQp9hkujM/edit#slide=id.g133aaa1b952_0_130) and Bonnie has reviewed.

**Comment by ExperimentsInHonesty** [comment]
Go through the presentation, looking for words that are not already in our [glossary](https://github.com/hackforla/guides/wiki/Glossary) and add them to this issue #103

**Comment by SheIsBukki** [comment]
Exon left a comment on [Slack](https://hackforla.slack.com/archives/C028T9XU9S5/p1656066049245959) on 24th of June

"Hey team. I won't be making it to the meeting today. Been having electricity issues all week. Thanks"

**Comment by ExperimentsInHonesty** [comment]
@Exonkenz  Please provide update using these guidelines
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by Exonkenz** [comment]
The words in the [Glossary spreadsheet](https://docs.google.com/spreadsheets/d/175pDnr-izub36J0xya6m9rSfIico6XnsStUz9KHSWIA/edit#gid=0) has successfully been transferred to [WIKI](https://github.com/hackforla/guides/wiki/Glossary)

**Comment by SheIsBukki** [comment]
@Exonkenz Please provide an update

Progress: "What is the current status of your project? What have you completed and what is left to do?"
Blockers: "Difficulties or errors encountered."
Availability: "How much time will you have this week to work on this issue?"
ETA: "When do you expect this issue to be completed?"
Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by SheIsBukki** [comment]
Exon left a comment on Slack https://hackforla.slack.com/archives/C028T9XU9S5/p1659356437599359

"Hi Team. I'll be taking a break. I have a lot of engagements I'm handling currently. Thank you for your time."

**Comment by edwardsarah** [comment]
Closed due to inactivity, if you'd like to rejoin the team please reach out in the guides slack channel.
